### ISSUE TITLE
Add inspect to phylanx

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/phylanx#101]
We should add inspect tool to Phylanx like the one we have for HPX.

**Comment by ct-clmsn** [comment]
@justwagle good call. just to clarify - a script that does some moderate amount of lint-testing?

**Comment by hkaiser** [comment]
@ct-clmsn we use it for HPX as part of the contiguous integration tests with very good results, see here for instance for a report it generates: https://8536-4455628-gh.circle-artifacts.com/0/tmp/circle-artifacts.N4s78oK/hpx_inspect_report.html
