### ISSUE TITLE
Phylanx fails to build with latest blaze

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/phylanx#1015]
The current master of Phylanx fails to build with the latest blaze.
The issue looks like SchurAssign was renamed to ModuloAssign in the following commit of blaze (https://bitbucket.org/blaze-lib/blaze/commits/1f8b93baeecb057f52e1e6e056ffee9a8acd87a6) and the change has not been incorporated into blaze tensor causing the build to fail. 

The build log is given below:
https://gist.github.com/justwagle/c349885d8009f9755239eba6c7c0397a

**Comment by hkaiser** [comment]
@justwagle This has been fixed by merging https://github.com/STEllAR-GROUP/blaze_tensor/pull/34. Could you please try again?

**Comment by justwagle** [comment]
@hkaiser That fixed it, thanks a lot.
