### ISSUE TITLE
Blaze header filename changed

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#1020]
Getting this error with current blaze:
```
/home/users/khuck/nightly/phylanx/phylanx/tools/buildbot/src/blaze_tensor/blaze_tensor/math/expressions/DTensNormExpr.h:76:10: fatal error: blaze/util/mpl/Bool.h: No such file or directory
 #include <blaze/util/mpl/Bool.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Apparently it's changed to Bools.h...

**Comment by hkaiser** [comment]
@taless474 do you think you could take care of this?

**Comment by taless474** [comment]
I have fixed the latest changes in Blaze up to [this commit](https://bitbucket.org/blaze-lib/blaze/commits/d7a05ba10b931fd05674808f011e529483c82505), [here](https://github.com/STEllAR-GROUP/blaze_tensor/tree/fixing_integral_constant). There are some new changes in including the headers (typetraits of containers only include the Forward files) and I was not able to compile that.
A few hours ago, Blaze has moved a few new files to another filename (FalseType and TrueType). Is it possible to have nightly tests with the older Blaze and wait for Blaze fundamental changes (changes in util) to complete?

**Comment by khuck** [comment]
Sure, I can build against whatever solid blaze release we want, until it stabilizes.  But it sounds like you are in-between versions now?

**Comment by taless474** [comment]
Yes, I think Blaze will be released soon. Right now, we can build Phylanx against Blaze_tensor master and [this commit](https://bitbucket.org/blaze-lib/blaze/commits/b0358851a6f23e29d8635bcb25e0db6981b5ebf9) of Blaze.

**Comment by khuck** [comment]
OK, changing to that commit.  I'll let you know if I run into issues.

**Comment by hkaiser** [comment]
@khuck this was fixed by merging https://github.com/STEllAR-GROUP/blaze_tensor/pull/37. Please switch your builds back to using Blaze and BlazeTensor master.

**Comment by khuck** [comment]
Will do
