### ISSUE TITLE
Phylanx install issue

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1026]
It should be possible to delete the phylanx source directory after installing phylanx. Unfortunately, Phylanx won't load if you do this. However, if you delete everything but the so files like this:
```
cd ~/phylanx # phylanx source dir
rm -f $(find . -type f -a ! -name \*.so\*)
```
Phylanx can run.

**Comment by hkaiser** [comment]
Could you please delete all files after installation and run any Phylanx application with `--hpx:debug-hpx-log=<filename>` and post the produced output (could be large) somewhere?

**Comment by stevenrbrandt** [comment]
Removal of `/home/jovyan/phylanx/build/lib/libhpx_phylanxd.so.0.0.1` triggers the problem.

Note the error is this:
```
Traceback (most recent call last):
  File "p.py", line 8, in <module>
    @Phylanx(performance='x')
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 62, in __init__
    self.backend = self.backends_map[self.backend](f, python_ast, kwargs)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 434, in __init__
    self.wrapped_function.__name__, self.__src__)
RuntimeError: p.py(10, 4): couldn't find function 'if' in symbol table: HPX(bad_parameter)
```

**Comment by stevenrbrandt** [comment]
I attempted to do what you asked.
```
from phylanx import Phylanx, PhylanxSession

PhylanxSession.config([
        'hpx.debug-hpx-log!=diag.txt',
        'hpx.os_threads!=1',
])

@Phylanx(performance='x')
def fib(n):
    if n < 2:
        return n
    else:
        return fib(n-1)+fib(n-2)

fib(5)
print(fib.__perfdata__)
```
Does not create diag.txt

**Comment by hkaiser** [comment]
Could you try this instead, please (command line options can be added verbatim as configuration):
```
PhylanxSession.config([
        '--hpx:debug-hpx-log=diag.txt',
        'hpx.os_threads!=1',
])
```

**Comment by stevenrbrandt** [comment]
[diag.txt](https://github.com/STEllAR-GROUP/phylanx/files/3531008/diag.txt)

**Comment by stevenrbrandt** [comment]
This was an improperly set LD_LIBRARY_PATH. Sorry.
