### ISSUE TITLE
Define is not working as expected

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/phylanx#106]
Define is not working as expected.
An example of this would be the one seen in the LRA example where defines inside the body of the loop were not getting executed more than once and each subsequent iteration of the loop was using old values.

**Comment by stevenrbrandt** [comment]
@justwagle is this still an issue for you?

**Comment by justwagle** [comment]
@stevenrbrandt Looks like this has been fixed with the new compiler update.
My testcase:
Physl code from issue #288 
```
$ cat def.physl 
define(k, 0)
define(iterations, 3)

while(k < iterations,
   block(
       define(a, k + 1),
       cout(a),
       store(k, k + 1)
   )
)

```
Running with the interpreter produces the following correct output:
```
./physl def.physl 
1
2
3
```

**Comment by stevenrbrandt** [comment]
My test passes too.
