### ISSUE TITLE
Phylanx no longer builds with HPX+APEX enabled

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#1078]
Because of the refactoring changes, something in the HPX installation needs to include the APEX build, so that Phylanx can build against it.  for example:

```
CMake Error at tools/buildbot/src/hpx/cmake/HPX_AddComponent.cmake:180 (add_library):
  Target "phylanx_component" links to target "hpx::apex" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/CMakeLists.txt:96 (add_hpx_component)
```

All of the failures are here: http://omega.nic.uoregon.edu:8020/#/builders/5/builds/41/steps/14/logs/stdio

**Comment by hkaiser** [comment]
@khuck what do we need to do in Phylanx to fix things?

**Comment by khuck** [comment]
@hkaiser I think it's an HPX fix.  libhpx_apex.so will have to be installed, along with the appropriate link/include flags for the dependencies.  We can talk about it in Denver this week...

**Comment by khuck** [comment]
Fixed in HPX
