### ISSUE TITLE
Phylanx compilation error with the lastest blaze

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/phylanx#1111]
Phylanx fails to compile with the latest (02/14/2020) blaze. 
The compilation log is found here: https://gist.github.com/justwagle/f5de5bf24690dec5695abac9429695d4
The following change in blaze may be related : https://bitbucket.org/blaze-lib/blaze/commits/e5334e3d8b643512a4b819d26ae1c7f38de20b75

**Comment by hkaiser** [comment]
There have been made even more profound changes to blaze recently. I'm in contact with the blaze author to resolve those. Please try to use an older Blaze commit for now until the issues have been resolved.

**Comment by hkaiser** [comment]
This should be fixed once https://github.com/STEllAR-GROUP/blaze_tensor/pull/58 is merged.
