### ISSUE TITLE
Strange behavior from Physl code

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1180]
If b0 is printed out before it's passed to the function, it's what you would expect from its definition. Inside the function, however, it's an empty list.

```
define(
    lra, x, y, alpha, iterations, enable_output,
    block(
        cout("b0",x),
        define(
            weights,
            constant(
                0,
                slice( shape(x), 1)
            )
        ),
        weights
    )
)
define(a2,1e-05)
define(a3,750)
define(a4,0)
define(b0,vstack(list(hstack(list(1,2)),hstack(list(3,4)))))
define(b1,hstack(list(0,1,0,1)))
cout("b0=",b0)
lra(b0,b1,a2,a3,a4)
```
The output is
```
b0= [[1, 2], [3, 4]]
b0 list()
physl: exception caught:
cc.physl(9, 24): shape:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ir::range'): HPX(bad_parameter)
```

**Comment by stevenrbrandt** [comment]
Note that if you leave out the define
```
define(
            weights,
            constant(
                0,
                slice( shape(x), 1)
            )
        ),
        weights
```
the print statement correctly prints out the list.

**Comment by hkaiser** [comment]
@stevenrbrandt this is even stranger... I'll look into it.

**Comment by hkaiser** [comment]
@stevenrbrandt the problem was that the PhySL compiler didn't properly diagnose if a PhySL function/variable was defined using a name that was already used before. Everything works fine if you change the name `lra` above for something else.

Also, please see #1185 for a fix that diagnoses this kind of problem.

**Comment by stevenrbrandt** [comment]
@hkaiser I see, I was unaware that lra was now a plugin.

**Comment by stevenrbrandt** [comment]
@hkaiser since renaming my function from lra to lra_demo, all has been well.
