### ISSUE TITLE
Improper handling of defaults

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1206]
The following code fails to run
```
from phylanx import Phylanx

q = 57

@Phylanx
def hello(n=q):
    print("n:",n)

hello()
```
The problem is that the system tries to evaluate `q` with PhySL when (I believe) it should use Python.

Note that this variang works:
```
from phylanx import Phylanx

@Phylanx
def hello(n=57):
    print("n:",n)

hello()
```

**Comment by hkaiser** [comment]
This is a bug. However I wouldn't know how to fix it. This has to be done in the front end (on the Python side of things). Do you have any ideas?

**Comment by stevenrbrandt** [comment]
@hkaiser I'm pretty sure I can fix it.
