### ISSUE TITLE
Decide whether to invoke eval directly

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#121]
All primitives expose their functionality through their `eval` (or `eval_direct`) action. By default those are invoked asynchronously, i.e. run on a new HPX thread. For certain operations this creates too much overhead and could be optimized by invoking the corresponding direct action instead (`eval_direct`). In general it is not always possible to make the decision at compile time which of those actions to invoke. 

This ticket is asking for two functionalities

- [x] add compile-time heuristics to make that decision at compile time, if possible (for instance for constant values or simple mathematical expressions)
- [x] add a means of making this decision at runtime (this most probably involves instrumentation using APEX - @khuck)

In both cases this decision has to be made on a case by case basis, i.e. for each action invocation.

**Comment by hkaiser** [comment]
@ct-clmsn suggested today to allow for implementing this decision through executors. This would harmonize the execution of actions with other scheduling APIs we have. Using executors for actions will require to add the corresponding functionalities to HPX, though.

**Comment by ct-clmsn** [comment]
@hkaiser related to [hpx/issues#1544](https://github.com/STEllAR-GROUP/hpx/issues/1544)?

**Comment by hkaiser** [comment]
@ct-clmsn yep, that's the one.

**Comment by hkaiser** [comment]
This can be closed now. All the infrastructure for this functionality is now in place in HPX and Phylanx.
