### ISSUE TITLE
Failling tests when installed on python 3.8 or later

### ISSUE THREAD

**Issue by git-kale** [STEllAR-GROUP/phylanx#1218]
Phylanx can be installed on a python with a version greater than 3.7 but running the most basic tests is throwing error.

````
Docker: stellargroup/phylanx_base:prerequisites
Phylanx at commit: d48b611bbc5337bc14ba93e4bf3cb
Build cmd: cmake -H/phylanx_src -B/phylanx_src/build -DCMAKE_BUILD_TYPE=Debug -DHPX_DIR=/usr/local/lib/cmake/HPX/ -Dblaze_DIR=/usr/local/share/blaze/cmake/ -Dpybind11_DIR=/usr/local/share/cmake/pybind11/
````

Test Case:
https://github.com/STEllAR-GROUP/phylanx/blob/ce34d25e7550d04533d79fff96153f7d9c476953/tests/regressions/python/832_performance_data.py

Error generated:
https://gist.github.com/git-kale/3d2eecda353df11a0d10efe5953850f2

**Comment by hkaiser** [comment]
@rtohid Would you have the time to look into this? From what I can see this is caused by some changes in the AST introduced with Python 3.8.

**Comment by rtohid** [comment]
@hkaiser, you are right, [`ast.Constant`](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Constant) was added in 3.6.
@git-kale #1219 should resolve the issue. Please let me know if the issue persisted.

**Comment by git-kale** [comment]
@rtohid 
I changed the files in system according to ````commit : 0a1970cc1500f73956f482fd95bd780b06462f01````
And a new error has popped: https://gist.github.com/git-kale/85fae9e96dc66301ef648bf1eaf231fd

**Comment by rtohid** [comment]
@git-kale, hope this works.

**Comment by git-kale** [comment]
@rtohid 
````
AttributeError: 'PhySL' object has no attribute '_<data-type>'
FATAL: exception not rethrown

data-type=['bool','float','int','str']
````

**Comment by rtohid** [comment]
@gding2018, could you please provide the complete error message? Thank you.

**Comment by git-kale** [comment]
@rtohid 
https://gist.github.com/git-kale/607b3bb6c489ead4fe24d851fe528a0a

**Comment by rtohid** [comment]
@git-kale, thank you. It's a bit strange, this PR adds `_Constant` and should've prevented this issue. Let's see how [CI build](https://github.com/STEllAR-GROUP/phylanx/pull/1219/checks?check_run_id=919189234) goes. Meanwhile, you may want to double check and make sure that you do have [`PhySL._Constant`](https://github.com/STEllAR-GROUP/phylanx/blob/4f88014fa6f87054073f19e9c3f6a3998713b704/python/phylanx/ast/physl.py#L916) in the module getting loaded.

**Comment by rtohid** [comment]
@git-kale, it seems all tests pass on CircleCI. Please make sure the changes are reflected to the module you load during program execution.

**Comment by git-kale** [comment]
Okay, I'll check that and will inform you tomorrow

**Comment by git-kale** [comment]
@rtohid  https://gist.github.com/git-kale/9579c7e649d3c4f742433e467b943f8d This is the debug log generated after adding the folowing lines. 
````
from phylanx import PhylanxSession      
PhylanxSession.config(PhylanxSession.cfg + ["--hpx:debug-hpx-log=file"])
````
