### ISSUE TITLE
Should update XtX after the user loops in ALS

### ISSUE THREAD

**Issue by NanmiaoWu** [STEllAR-GROUP/phylanx#1220]
In ALS, `XtX` should be updated after the user loops. So, instead of in line 72 in https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/algorithms/als/als_csv.cpp#L72, XtX should be moved to line 86, which is just above the item loops.

**Comment by hkaiser** [comment]
@NanmiaoWu would you be able to create a PR for this?
