### ISSUE TITLE
Cannot get keys of a dictionary

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#1225]
As reported by @stevenrbrandt here: https://github.com/STEllAR-GROUP/docker-containers/issues/7

**Comment by stevenrbrandt** [comment]
This code sort of works.
```
from phylanx import Phylanx

@Phylanx
def foo():
    a = {"a":1,"b":2,"c":3}
    for k in a:
        print(k)

foo()
```
produces
```
list(c, 3)
list(b, 2)
list(a, 1)
```
Which is an improvement. However, it should produce
```
a
b
c
```

**Comment by stevenrbrandt** [comment]
@hkaiser I pushed a fix for the above problem to the PR.
