### ISSUE TITLE
Start time counter after reading input and slicing input in non-distributed als.py

### ISSUE THREAD

**Issue by NanmiaoWu** [STEllAR-GROUP/phylanx#1228]
Should start time counter after reading data and slicing the input data in als.py. So, should move `t0` from line 105 to line 110 (https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/algorithms/als/als.py#L105), which is consistent with the other two physl version of non-distributed als and distributed als.

**Comment by hkaiser** [comment]
@NanmiaoWu would you mind creating a PR for this?

**Comment by NanmiaoWu** [comment]
> @NanmiaoWu would you mind creating a PR for this?

Ah.. Sorry, I just saw it. Will do it.
