### ISSUE TITLE
Allow Phylanx to accept connecting localities

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1245]
The Phylanx notebook should have the option of being open to connecting localities so that computing resources can be expanded easily.

**Comment by stevenrbrandt** [comment]
@hkaiser actually, this might not need a change to Phylanx. Maybe callling with the right options to session init. I'll experiment.

**Comment by hkaiser** [comment]
@stevenrbrandt there are currently three ways available to achieve this. First you could pass the option `--hpx:expect-connecting-localities` to the session initializer:
```
from phylanx import PhylanxSession
config = PhylanxSession.cfg.append('--hpx:expect-connecting-localities')
PhylanxSession.config(config)
```

The other options is to add the option to the HPX environment variable `HPX_COMMANDLINE_OPTIONS`:
```
export HPX_COMMANDLINE_OPTIONS=--hpx:expect-connecting-localities
```
The value of this environment variable will be prepended to the command line before it is being processed.

Lastly, you can enforce the option through the environment directly:
```
export HPX_EXPECT_CONNECTING_LOCALITIES=1
```

**Comment by stevenrbrandt** [comment]
@hkaiser thanks.

Obviously, I'll have to turn off MPI to make use of this.

**Comment by hkaiser** [comment]
> Obviously, I'll have to turn off MPI to make use of this.

Not necessarily. Connecting localities will always use TCP, however, even if the base application relies on MPI for communication.

**Comment by hkaiser** [comment]
I think we can close this as there are ways to achieve the mentioned goal.
