### ISSUE TITLE
np.random or random.random is translated to randn

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/phylanx#1261]
`data["W0"] = np.random.random([data["hidden_nodes_sz"], data["input_nodes_sz"]])`

is translated to 
```

        store(
            slice(data, "W0"),
            randn(
                slice(data, "hidden_nodes_sz"),
                slice(data, "input_nodes_sz")

```

However there is no `randn` and we get 

`RuntimeError: /home/diehlpk/git/SOO/nn/nn.py(93, 17): couldn't find function 'randn' in symbol table: HPX(bad_parameter)`

**Comment by diehlpk** [comment]
Deleting the folder  `__physlcache__/ ` solved the problem.

**Comment by hkaiser** [comment]
See #1263 for a way to avoid this problem in the future.
