### ISSUE TITLE
Debug option does not work as expcted.

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#1294]
Setting the debug option to `true` should print the PhySL code at function definition not function call.

**NOT working**
```py
from phylanx import Phylanx

@Phylanx(debug=1)
def foo():
    return 1
```

**working**
```py
from phylanx import Phylanx

@Phylanx(debug=1)
def foo():
    return 1

foo()
```
with output:

```
define(
    foo,
    lambda(1)
)

```

**Comment by hkaiser** [comment]
@rtohid this is a side effect of the delayed compilation we have put in place a while ago. However I think we could simply compile the function right away if `debug=True` is set.

**Comment by rtohid** [comment]
Thanks @hkaiser. I get similar behavior with `debug=True`.

**Comment by hkaiser** [comment]
> Thanks @hkaiser. I get similar behavior with `debug=True`.

Sure, I didn't imply `debug=1` would be different from `debug=True`. What I meant is that we should change https://github.com/STEllAR-GROUP/phylanx/blob/master/python/phylanx/ast/physl.py#L515 to:
```
    if PhylanxSession.is_initialized or self.kwargs.get('debug', False):
```
to force compiling a function when it is seen first if `debug` is enabled.

**Comment by rtohid** [comment]
Thanks @hkaiser. I'd misunderstood. This works, I'll create a pull request later today.
