### ISSUE TITLE
Cannot import Phylanx on Fedora

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#130]
When the attached Dockerfile is used to build Phylanx on Fedora, the resulting Python library does not run.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/__init__.py", line 65, in <module>
    init_hpx_runtime()
RuntimeError: partitioner::add_resource: Creation of 2 threads requested by the resource partitioner, but only 1 provided on the command-line.
[root@9d0aeb8d4ab0 build]#
```
[PhylanxReleaseDockerfile.txt](https://github.com/STEllAR-GROUP/phylanx/files/1560609/PhylanxReleaseDockerfile.txt)

**Comment by stevenrbrandt** [comment]
Update: The problem appears to be that Phylanx doesn't run on a 2-socket machine. The issue has nothing to do with Fedora. The docker image stevenrbrandt/phylanx.release runs without difficulty on a 1-socket machine, but produces an error on a 2-socket machine.

**Comment by hkaiser** [comment]
All of this makes les and less sense. But thanks for the update.

**Comment by stevenrbrandt** [comment]
If I compile with
HPX_WITH_MAX_CPU_COUNT=80
HPW_WITH_MORE_THAN_64_THREADS=ON
everything seems to work. I guess the problem is that HPX couldn't figure out the number of CPUs?

**Comment by stevenrbrandt** [comment]
The need to compile something like this in is a potential problem if anyone wants to use HPX in a container.

**Comment by khuck** [comment]
@stevenrbrandt in the buildbot scripts, I use both.  for example:

```
cmake -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/usr/local/packages/boost/1.65.0-gcc7 -DTCMALLOC_ROOT=/usr/local/packages/gperftools/git-gcc7 -DHPX_WITH_MALLOC=tcmalloc -DHWLOC_ROOT= -DCMAKE_INSTALL_PREFIX=. -DHPX_WITH_TOOLS=OFF -DHPX_WITH_THREAD_IDLE_RATES=ON -DHPX_WITH_PARCELPORT_MPI=OFF -DHPX_WITH_PARCEL_COALESCING=OFF -DHPX_WITH_APEX=TRUE -DAPEX_WITH_ACTIVEHARMONY=TRUE -DACTIVEHARMONY_ROOT=/usr/local/packages/activeharmony/4.6.0-gcc -DAPEX_WITH_OTF2=TRUE -DOTF2_ROOT=/usr/local/packages/otf2-2.1 -DAPEX_WITH_PAPI=TRUE -DPAPI_ROOT=/usr/local/packages/papi/papi-knl/5.5.0/ -DHPX_WITH_APEX_NO_UPDATE=FALSE -DHPX_HAVE_MORE_THAN_64_THREADS=ON -DHPX_WITH_MAX_CPU_COUNT=72 /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/src/hpx
```

however, I get this message from the HPX configure:

```
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    HPX_HAVE_MORE_THAN_64_THREADS
```

See [this build log](http://ktau.nic.uoregon.edu:8020/builders/x86_64-gcc7-release/builds/193/steps/Get%20and%20Configure%20HPX/logs/stdio) for an example.

**Comment by hkaiser** [comment]
@khuck you don't have to specify `HPX_HAVE_MORE_THAN_64_THREADS`, that's more of an internal variable set depending on `HPX_WITH_MAX_CPU_COUNT` (which defaults to 64).
