### ISSUE TITLE
Pattern matching is not working for negative values

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/phylanx#131]
Negative values passed to primitives results in the following exception : 
``` 
{function}: phylanx::execution_tree::compiler::operator()()
{file}: /home/bibek/Dropbox/GitHub/phylanx/src/execution_tree/compiler/compiler.cpp
{line}: 376

{what}: couldn't fully pattern-match the given expression: -1: HPX(bad_parameter)

terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
  what():  couldn't fully pattern-match the given expression: -1: HPX(bad_parameter)
```

To Reproduce: 
change any one of the parameters in the slicing primitive in the lra_csv example ( [https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/algorithms/lra_csv.cpp](url) ) from the repository to -1. For example, changing slice(file_read_csv(filepath), 0, 569, 0, 30) to slice(file_read_csv(filepath), 0, 569, -1, 30) as seen in the code snippet below.

```
char const* const read_x_code = R"(block(
    //
    // Read X-data from given CSV file
    //
    define(read_x, filepath,
        slice(file_read_csv(filepath), 0, 569, -1, 30)
    ),
    read_x
))";

**Comment by hkaiser** [comment]
@justwagle see #132 and please report back on whether this solves your issue.

**Comment by justwagle** [comment]
@hkaiser That fixed it. Thank you very much.
