### ISSUE TITLE
PhySL interpreter throws exception: the target (destination) does not match the action type

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#1321]
PhySL interpreter throws an exception on almost any code. The following:
```console
random(list(3,4), list("uniform_int", -3, 2))
```
produces:
```console
physl: exception caught:
the target (destination) does not match the action type (symbol_namespace_iterate_action): HPX(bad_parameter)
```

Please note that the code's equivalent using python works fine:
```python
from phylanx import Phylanx
import numpy as np

@Phylanx()
def rand():
    return np.random([3,4],["uniform_int", -3, 2])
	
print(rand())
```
produces
```console
[[-3.  2.  0.  0.]
 [-2.  2.  1. -3.]
 [-1. -2.  0.  0.]]
```

**Comment by hkaiser** [comment]
@taless474 What options did you use when running the interpreter?

**Comment by taless474** [comment]
Command args are: --hpx:threads=1 C:\Users\Bita\Desktop\physl.txt --print

**Comment by hkaiser** [comment]
@taless474 FWIW, I have it reproduced. Let's see...

**Comment by hkaiser** [comment]
@taless474 STEllAR-GROUP/hpx#5271 should fix the issue, please verify.
