### ISSUE TITLE
Primitives for stacking/combining matrices

### ISSUE THREAD

**Issue by justwagle** [STEllAR-GROUP/phylanx#144]
We need something that is opposite of slicing i.e. joining matrices.  Also,  It would be useful to have primitives that provides similar functionality as hstack and vstack in numpy.

**Comment by ct-clmsn** [comment]
@justwagle here are a couple reference documents that might help sort out a generalized solution.

https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.column_stack.html
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.stack.html
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.dstack.html

**Comment by hkaiser** [comment]
This was fixed by merging #170
