### ISSUE TITLE
Generate expression tree topology in DOT format

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#153]
This is necessary as an option for writing the expression tree topology to disk for later analysis.

**Comment by ct-clmsn** [comment]
provide functionality to save an expression tree to a file; provide functionality to load an expression tree from a file into memory. this should help with reproducibility, visualization, and analysis. consider providing a small program that can convert the stored expression tree into a variety of visualization formats.

**Comment by hkaiser** [comment]
@ct-clmsn we can already store/load the AST. Would that be sufficient? We can easily create the expression tree from the AST.

**Comment by ct-clmsn** [comment]
@hkaiser What exists is sufficient. I've a lingering (maybe _nagging_ is a better word) feeling that a binary format is something that might be revisited later.
