### ISSUE TITLE
tangent integration

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#19]
Test Python bindings for interoperability with SymPy.

**Comment by ct-clmsn** [comment]
@hkaiser @stevenrbrandt do ya'll mind if this ticket is changed from sympy to tangent? tangent provides the specific capability that we originally aimed to inherit from sympy (auto-differentiation).

**Comment by stevenrbrandt** [comment]
@ct-clmsn, Do we want to limit ourselves to auto-differentiation? I'm not clear on the pros and cons of SymPy  vs. Tangent at the moment.

**Comment by hkaiser** [comment]
This is a duplicate of #225. Closing...
