### ISSUE TITLE
Cmake can't find HPX when HPX_DIR is set in environment varibales

### ISSUE THREAD

**Issue by hapoo** [STEllAR-GROUP/phylanx#243]
If `HPX_DIR` is set in environment variable rather than explicitly in `-DHPX_DIR=PATH`, cmake fails to find HPX.
There is no issue in finding other dependencies with environment variables.

**Comment by hkaiser** [comment]
@hapoo CMake relying on environment variables is unusual. The reason is that CMake is not able to detect whether an environment variable has changed since its last invocation, thus relying on those could invalidate an existing CMakeCache.txt.
