### ISSUE TITLE
Can not create a list or a vector of previously defined variables

### ISSUE THREAD

**Issue by scheherzade** [STEllAR-GROUP/phylanx#244]
Creating a list or of previously defined variables gives the following error message.

```scheme
define(test_list,block(
                define(a, 5),
                define(b, 6),
                define(mylist,'(a, b))
                )
)
apply(test_vec, sys_argv)
```
```
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>' 
what():  couldn't fully pattern-match the given expression: '(a, b): HPX(bad_parameter)
```
In case of vector:
```scheme
define(test_vec, block(
                define(a, 5),
                define(b, 6),
                define(myvec, [a, b])
                )
)
apply(test_vec, sys_argv)
```
```
terminate called after throwing an instance of 'hpx::detail::exception_with_info<hpx::exception>'
 what():  Error! Expecting <list><real>","
```

**Comment by ct-clmsn** [comment]
@scheherzade would vstack and hstack be sufficient?

block(
    define(a, 5)
    , define(b, 6)
    , define(myvec, hstack(5, 6)) # creates a horizontal array or 'list'
    )
)

**Comment by hkaiser** [comment]
@scheherzade #251 should solve this. Please be aware that instead of using `[...]` or `'(...)` to create a vector or a list in PhySL code you should use `make_vector()` or `make_list()`.

**Comment by hkaiser** [comment]
@ct-clmsn this is a good suggestion (sorry I saw it too late). It may make `make_vector()` obsolete to begin with. The `make_list()` primitive however will still be required.

**Comment by justwagle** [comment]
@hkaiser I will get working on adding mixing arguments of different dimensionality in hstack and vstack.

**Comment by stevenrbrandt** [comment]
As near as I can tell, (1) make_list() and make_vector() do not exist, and hstack() and vstack() take exactly 2 arguments. However, hstack vstack are specified like this: '"vstack(_1, __2)"', with two underscores in front of the 2. I suspect that the extra underscore is supposed to be some sort of wild card for additional arguments, but if so, it doesn't work.

**Comment by ct-clmsn** [comment]
@hkaiser sounds good. thanks!

**Comment by hkaiser** [comment]
> As near as I can tell, (1) make_list() and make_vector() do not exist, and hstack() and vstack() take exactly 2 arguments. However, hstack vstack are specified like this: '"vstack(_1, __2)"', with two underscores in front of the 2. I suspect that the extra underscore is supposed to be some sort of wild card for additional arguments, but if so, it doesn't work.

Please see #251, that should address both of your concerns. And yes, `__2` means one or more arguments.
