### ISSUE TITLE
PhySL Modifies Untouched Variable

### ISSUE THREAD

**Issue by scheherzade** [STEllAR-GROUP/phylanx#245]
The following PhySL code:

```scheme
define(A,[[1,2,3],[4,5,6]])
define(B,[[3,4,5],[2,7,9]])
store(A,B+A)
cout(A)
cout(B)
```
Produces output:
```
[[4, 6, 8], [6, 12, 15]]
[[4, 6, 8], [6, 12, 15]]
```

B is not supposed to be changed.

**Comment by hkaiser** [comment]
This is caused by the add primitive, which 'reuses' the left-hand-side memory for the generated result.
