### ISSUE TITLE
tune cmake install functionality for python

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#25]
phylanxrun.py and the compiled phylanx python-c module ( phylanx.cpython-*.so) currently do not install into the CMAKE_INSTALL_PREFIX directory. The files are installed into the cmake build directory. 

In the python-c module's case, it does not install into the default PYTHONPATH. Strongly encourage some type of cmake-setup.py solution. The documentation on [this site](https://bloerg.net/2012/11/10/cmake-and-distutils.html) looks like a useful guide.

The  phylanx python-c module should install into a directory like "$INSTALL_DIR/lib/pythonX/site-packages/phylanx/" where X is the correct version of python - setup.py will do this automagically. The python module also needs an [`__init__.py`](https://docs.python.org/3/tutorial/modules.html) file.

**Comment by hkaiser** [comment]
I'm not very knowledgeable in this domain - any help would be appreciated. 
@stevenrbrandt would that be something you could take care of?

**Comment by hkaiser** [comment]
This has been partially addressed by merging #29. More work is required for this, though.

**Comment by hkaiser** [comment]
I think this can be closed now. The Python extension has been properly integrated into the build and installation process. Feel free to reopen if something is still missing.
