### ISSUE TITLE
Map Numpy functionalities to Phylanx primitives

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#256]
Numpy methods should automatically get mapped to the Phylanx primitives- when available.

**Comment by hkaiser** [comment]
pybind11 directly supports NumPy (see http://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html). It should be possible to utilize this for our needs.

**Comment by hkaiser** [comment]
Here is a list of things we have to today that already could be mapped to from NumPy (please add more as we go):

- [ ] arithmetic (`*`, `+`, `/`, `-`, unary `-`), comparison (`==`, `!=`, `>`, `>=`, `<`, `<=`), and boolean (`||`, `&`, `!`, `np.any`, `np.all`) operations
- [ ] `np.cross`, `np.dot`
- [ ] `np.diag`
- [ ] `np.argmin`, `np.argmax`
- [ ] `np.determinant`
- [ ] `np.inverse`, np.transpose`
- [ ] `np.exp`
- [ ] `np.hstack`, `np.vstack`
- [ ] `np.shape`
- [ ] `np.identity`
- [ ] `np.linspace`, `np.linearmatrix`
- [ ] `np.power`
- [ ] `np.random.*`
- [ ] `np.sqrt`
- [ ] `np.transpose`
- [ ] slicing operations

**Comment by hkaiser** [comment]
@stevenrbrandt, @rtohid any news on this?

**Comment by hkaiser** [comment]
@stevenrbrandt, @rtohid what's the current status on this?

**Comment by stevenrbrandt** [comment]
@hkaiser not finished

**Comment by hkaiser** [comment]
I believe we can close this as the frontend properly detects all numpy functions and maps those onto the existing primitives.
