### ISSUE TITLE
possible missing header file in column_set

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#284]
Possible include issue on at this [line](https://github.com/STEllAR-GROUP/phylanx/blob/47b0af1e14291dd7fedd35563610720b469b7ffa/src/execution_tree/primitives/column_set.cpp#L25). g++ 6.+ creates compile-time include errors on this line. the errors are related to a missing blaze header file that defines the blaze::elements function. Adding `#include <blaze/math/Elements.h>`  to [this line](https://github.com/STEllAR-GROUP/phylanx/blob/47b0af1e14291dd7fedd35563610720b469b7ffa/src/execution_tree/primitives/column_set.cpp#L25) resolves the compilation issue.

**Comment by justwagle** [comment]
Thank you very much Chris. I will take care of it.

**Comment by ct-clmsn** [comment]
@justwagle no problem! thanks for looking into it. not sure if it's a compiler issue or a header inclusion issue on the blaze side of things.
