### ISSUE TITLE
Value of a variable defined inside a while loop stays unchanged

### ISSUE THREAD

**Issue by scheherzade** [STEllAR-GROUP/phylanx#288]
If a variable is defined inside a while loop, value of the variable stays the same through all the iterations.

 ```
define(k,0)
define(iterations,3)

while(k<iterations,
block(define(a,k+1),
cout(a),
store(k,k+1)))
```
result:
```
1
1
1
```

**Comment by hkaiser** [comment]
Yes, this is a known issue (see #106). I don't have a solution for this at this point.
