### ISSUE TITLE
Python Slicing/Indexing Semantic Mismatch

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#295]
There is a semantic mismatch between PhySL and Python with regard to subscripting arrays. The following short program demonstrates the problem.

```python
from phylanx.ast import *
import numpy as np

@Phylanx()
def sliceme(a):
    return a[0:1]

a = np.array([1,2,3])
v1 = a[0:1]
v2 = sliceme(a)

print('Python=',type(v1),v1) # Prints an array
print('PhySL=',type(v2),v2) # Prints a value

assert v1[0] == v2[0]
```

The way I think this should work
```
Python Code -> PhySL Code
a[i:j] -> slice(a,[i,j]) -> produce a vector
a[i] -> slice(a, i) -> produce a value
a[i:j:k] -> slice(a,[i,j,k]) -> produce a vector with step size k
a[i:j,n:m] -> slice(a,[i,j],[n,m]) -> produce a matrix
a[i:j,n] -> slice(a,[i,j],n) -> produce a vector
a[n,i:j] -> slice(a,n,[i,j]) -> produce a vector
a[n,m] -> slice(a,n,m) -> produce a value
```

**Comment by stevenrbrandt** [comment]
@justwagle Here's the ticket describing how I think the slicing primitive ought to work. It would provide a more natural mapping onto Python semantics.

**Comment by hkaiser** [comment]
@stevenrbrandt could you please elaborate which of the cases you listed doesn't work the way you'd expect?

**Comment by stevenrbrandt** [comment]
Essentially, a slice of an array should be an array (which is what Python/Numpy does). In Physl, if the slice is of size 1, it gets converted into a value and any attempt to index it results in an exception. In general, a slice a[i:j] does not have a different dimensionality than the object it's applied to. Indexing, however, does produce a different, lower dimensionality.

Apart from the semantic mismatch with Python, I think that returning a different type of object depending on whether the slice is of size 1 or more than 1 is likely to lead to more complex and brittle code. For loops, e.g. "for v in a[n:m]:" would throw an exception if n+1 happened to equal m, etc. Yes, you could make an "int" iterable in PhySL, but that would be yet another semantic mismatch with Python.

**Comment by hkaiser** [comment]
Changing this will have far reaching consequences for other primitives that assume otherwise. For instance

    A = B + C[1:2, 1:2]

(where A, B, and C are matrices) currently works if the right term (the `C[:,:]`) returns a single value, but it might not work anymore if it resolves to a matrix of size [1, 1]. I'm not opposed to changing the semantics as you outlined, we just have to be very careful as this would break a lot of existing code.

**Comment by stevenrbrandt** [comment]
I agree that it will probably break some existing code, but I really believe it's necessary. The tangle of problems related to this semantic mismatch will only get more serious with time if it's left as it is.

**Comment by hkaiser** [comment]
Ok, let's do it. @justwagle could you start with changing the semantics of the slice primitives, please? Let's see what will actually break.

**Comment by justwagle** [comment]
@hkaiser yes, I will do that.
