### ISSUE TITLE
lra+blaze compile error

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#316]
compile error with lra.cpp. gcc 6.3.0 complains with a 'blaze/Math.h' no such file or directory. CMakeCache.txt has blaze_DIR set to the correct install directory for blaze.

**Comment by khuck** [comment]
Hartmut fixed this with the fixing_external_projects branch... hasn't been merged yet.

**Comment by hkaiser** [comment]
@ct-clmsn please see #317 for a fix.

**Comment by ct-clmsn** [comment]
@khuck @hkaiser thanks - I was slow keeping up with the mods this weekend. will close via #317
