### ISSUE TITLE
-1 is not the same as -(1)

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#356]
The last two calls to cout should print the same thing, but physl interprets -(1) and -1 differently.
```
block(
    define(a,[1,2,3,4]),
    cout(slice(a,'(0,4))),
    cout(slice(a,'(0,-1))),
    cout(slice(a,'(0,-(1))))
)
```

**Comment by hkaiser** [comment]
As stated before, please use `make_list()` instead of `'()`. Things will just work.
