### ISSUE TITLE
Phylanx in Python hangs randomly

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#359]
When I execute the program below from the command line, it hangs about 50% of the time.
```
import numpy as np
import phylanx
from phylanx.ast import *

@Phylanx()
def f1():
    a = [1,2,3,4]
    return a[1]

assert f1() == 2

@Phylanx()
def f2():
    a = [1,2,3,4]
    return a[1:3]

assert np.all(f2() == np.array([2,3]))

@Phylanx()
def f3():
    a = [1,2,3,4]
    print(shape(a))
    return a[0:-1]

print(f3())
```

**Comment by hkaiser** [comment]
@stevenrbrandt Could you please minimize this example? My suspicion is that the print functionality is not quite bug-free yet, it would be nice to have that confirmed...

**Comment by hkaiser** [comment]
@stevenrbrandt is this still an issue for you (we have changed things slightly recently, so it might have been fixed...)?

**Comment by stevenrbrandt** [comment]
On the latest Phylanx this is aborting for me with no message :(
It's happening during compilation of the first function in the test code. When I take the code:
```
define(
    f1,
    block(
        define(a, [1,2,3,4]),
        slice(a,1)
    )
)
```
And run it through physl I'm seeing
```
$ physl f1.py
physl: exception caught:
f1.py(3, 5): couldn't find function 'block' in symbol table: HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
This is an unrelated problem and most likely caused by the plugins not being built.
