### ISSUE TITLE
HPX and Phylanx Command Line Argument Handling is mixed up

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#395]
Example case:
```
$ physl -t 1 -c 1+2 -p
physl: exception caught:
Failed to open the specified file: 1: HPX(filesystem_error)
$ physl --hpx:threads=1 --transform trans.physl -c 1+2 -p
3
```

**Comment by stevenrbrandt** [comment]
Yes, I know about that.

The thing is, I can run hpx on such machines, just not phylanx.

I thought you said that the issue could be fixed for phylanx with a command
line arg.

--Steve
