### ISSUE TITLE
eigen3 to blaze migration

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#40]
Migrate Phylanx data primitives from [Eigen] to [Blaze].

- [x] Update the CMake scripts to find Blaze - PR #71 
- [x] The big sweep - PR #78
  - [x] [Serialization]
  - [x] [`node_data`]
  - [x] Update [primitives]
  - [x] Port [tests] to Blaze
- [x] Update the CI System
  - [x] @khuck's buildbot
  - [x] [AppVeyor]
  - [x] [Circle-CI]
- [x] Update build instructions on [wiki]
- [x] Integrate HPX into Blaze for parallelizing matrix operations
  - [x] PR on Blaze project: https://bitbucket.org/blaze-lib/blaze/pull-requests/15

[Eigen]: http://eigen.tuxfamily.org/index.php?title=Main_Page
[Blaze]: https://bitbucket.org/blaze-lib/blaze
[Serialization]: https://github.com/STEllAR-GROUP/phylanx/tree/master/phylanx/util/serialization
[`node_data`]: https://github.com/STEllAR-GROUP/phylanx/blob/master/phylanx/ir/node_data.hpp
[primitives]: https://github.com/STEllAR-GROUP/phylanx/tree/master/phylanx/execution_tree/primitives
[AppVeyor]: https://ci.appveyor.com/project/hkaiser/phylanx
[Circle-CI]: https://circleci.com/gh/STEllAR-GROUP/phylanx
[tests]: https://github.com/STEllAR-GROUP/phylanx/tree/master/tests/unit
[wiki]: https://github.com/STEllAR-GROUP/phylanx/wiki/Build-Instructions

**Comment by parsa** [comment]
CMake issue:
* Blaze CMake scripts do not provide any information about the version and the location of the library.
* vcpkg installation does not provide `blaze-config.cmake` Microsoft/vcpkg/issues/1996
* Library verification can be temporarily bypassed by setting `PHYLANX_SKIP_BLAZE_CHECK` to any value. (e.g. `cmake -DPHYLANX_SKIP_BLAZE_CHECK=On <other flags> <directory>`)

**Comment by parsa** [comment]
@khuck what's Blaze status on your machines?

**Comment by khuck** [comment]
The builds are already building blaze.

**Comment by khuck** [comment]
...but the phylanx builds are failing.

http://ktau.nic.uoregon.edu:8020/builders/ppc64le-clang5-release/builds/54/steps/Compile%20Phylanx/logs/stdio

**Comment by khuck** [comment]
Why is the path to Blaze non-standard?  That is, why not -Dblaze_DIR=... instead of -Dblaze_INCLUDE_DIR?

**Comment by parsa** [comment]
Because as far as I can tell Blaze's CMake scripts don't reveal or include the the path of the header files. Please use `blaze_INCLUDE_DIR` instead.

**Comment by khuck** [comment]
build finished, tests failed.  http://ktau.nic.uoregon.edu:8020/waterfall

It still requires eigen3, or else configure fails.

**Comment by parsa** [comment]
@hkaiser I don't know which build you're talking about, but I'm looking at [build 72](http://ktau.nic.uoregon.edu:8020/builders/x86_64-gcc7-release/builds/72/steps/Test%20Phylanx/logs/stdio) and it shows only the Python tests fail.

**Comment by khuck** [comment]
Sorry, I was a bit misleading.  I was just letting you know that without setting -Deigen3_DIR, configure will fail.  For now, I have left it in for the buildbot scripts.   You should change CMakeLists.txt to not require eigen3 if the phylanx code has changed to blaze.

**Comment by parsa** [comment]
It also doesn't need Eigen as you can see in the [log of the CMake run](http://ktau.nic.uoregon.edu:8020/builders/x86_64-gcc7-release/builds/72/steps/Configure%20Phylanx/logs/stdio):

```
CMake Warning:
  Manually-specified variables were not used by the project:

    Eigen3_DIR
```

I've already either removed or updated all references to Eigen in the code.

**Comment by parsa** [comment]
Tasks done.
