### ISSUE TITLE
missing block in symbol table

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#402]
Running `phylanx_als_csv.py` and `phylanx_lra_csv.py` generates the following execution error:

```
File "phylanx_als_csv.py", line 10, in <module>
  @Phylanx("PhySL")
File "phylanx/ast/transformation.py", line 558, in __init__
   et.compile(self.__src__, self.cs)
RuntimeRror: <unknown>(11,0): couldn't find function 'block' in symbol table: HPX(bad_parameter)
```

**Comment by stevenrbrandt** [comment]
There was a version or two of phylanx where the plugins didn't get installed properly. This might be fixed by "git pull."

**Comment by ct-clmsn** [comment]
@hkaiser @stevenrbrandt i've a directory in $INSTALL_DIR/lib/phylanx with 6 shared objects libphylanx_[arithmetics, booleans, controls, fileio, listops, matrixops].so; the directory has been exported  into $LD_LIBRARY_PATH and $PYTHONPATH. is that the correct behavior for the installer?

**Comment by hkaiser** [comment]
@ct-clmsn Sounds about right... Does it still refuse to work?

**Comment by ct-clmsn** [comment]
@hkaiser @stevenrbrandt - yep. on the upside, the C++ programs lra_csv and als_csv work correctly. is there something specific about how python works (LD_PRELOAD) on linux that would cause the python-phylanx implementations to misbehave?

**Comment by ct-clmsn** [comment]
@hkaiser @stevenrbrandt I'm going to close this bug since we have solution. The solution is a documentation update and maybe some script-level tooling.

**Comment by khuck** [comment]
It still doesn't work on OSX, even when setting DYLD_INSERT_LIBRARIES and DYLD_FORCE_FLAT_NAMESPACE=1

**Comment by hkaiser** [comment]
@khuck yes, we know... It's on the list of things to work on.
