### ISSUE TITLE
PhySL hangs randomly

### ISSUE THREAD

**Issue by tianyi93** [STEllAR-GROUP/phylanx#408]
Command Line:
```
physl test1.physl
```

PhySL code:
```
define(linear_regresion, matrix, 
	block(
		define(xlo,0),
		define(xhi,shape(matrix,0)),
		define(column_x,slice(matrix, make_list(xlo,xhi),0))
	))
```

**Comment by hkaiser** [comment]
Yes, all of the hangs seem to be related to printing. So somewhere we still have a GIL problem lurking in the woods...

**Comment by hkaiser** [comment]
Please try again using #483, this should solve this issue.

**Comment by hkaiser** [comment]
I'm closing this for now. Please reopen if the issue still persists.
