### ISSUE TITLE
Different results from numpy when performing arithmetic operations between a vector and a matrix with only one column

### ISSUE THREAD

**Issue by scheherzade** [STEllAR-GROUP/phylanx#410]
The result of performing `-`, `+`, `/`, and `*` operations between a vector and a matrix with only one column in Phylanx is different from NumPy.  
Generally to be able to perform this kind of operations between a vector and a matrix in NumPy, size of the vector should be equal to number of columns of the matrix, which is the way it is implemented in Phylanx. But in NumPy for cases where the matrix has only one column, you could still perform the operations, which is missing from Phylanx. 
e.g.
```python
np.array([1, 2]) + np.array([[3],[4]])
```
returns
```
array([[4, 6],
       [6, 8]])
```

while in PhySL: 
```
[1, 2] + [[3], [4]]
```
returns:
```
__add$0/0$1$1:: vector size does not match number of matrix columns: HPX(bad_parameter)
```

**Comment by parsa** [comment]
Documentation for NumPy's broadcasting behavior: <https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html>.

Documentation for NumPy equivalents for each of the problematic primitives:
* <https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.add.html>
* <https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.subtract.html>
* <https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.multiply.html>
* <https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.divide.html>
