### ISSUE TITLE
gnu compilation issues

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#420]
gcc-6 and gcc-7 whine about the phylanx plugin factory macros - is a fix or workaround available? Preferably one that does not include switching to a different compiler!

**Comment by hkaiser** [comment]
It's an HPX issue (if you're talking about what I think you see). I will try to do something about this.

**Comment by ct-clmsn** [comment]
@hkaiser recompile of hpx and phylanx seems to have done the trick. thanks! will close.
