### ISSUE TITLE
python _Assign functionality for subscripted matrices

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#440]
Currently expressions such as:

```python
from phylanx.ast import Phylanx

@Phylanx
def update_values(mat, N):
    for i in range(N):
        for j in range(N):
            mat[i, j] = 0.0
```
break in the following file/line `phylanx/python/phylanx/ast/transformation.py:287 (the Python ast.Subscript type does not have an 'id' member variable)`

**Comment by justwagle** [comment]
@ct-clmsn You should be able to use the set primitive. 
set (input, row_start, row_stop, row_steps  , col_start, col_stop, col_steps , value_to_set )
If you want to extract an element, slice should support that.

**Comment by ct-clmsn** [comment]
@justwagle thanks! should i start off by doing a PhySL implementation before going straight to python?

**Comment by justwagle** [comment]
@ct-clmsn I think python version would be better as @stevenrbrandt is already working on the ticket to add the missing functionality in python.

**Comment by ct-clmsn** [comment]
@stevenrbrandt go for it! @justwagle will continue to work on the python version to identify use-cases that need additional support.

**Comment by stevenrbrandt** [comment]
For reference, the sample code above should be rewritten like this:
```
from phylanx.ast import *
import numpy as np

N = 3
m = np.ones ((N,N))

@Phylanx("PhySL")
def update_values(mat, N):
   for i in range(N):
      for j in range(N):
        mat[i,j] = 0.0

m2 = update_values(m,N)
print(m2)
```

**Comment by stevenrbrandt** [comment]
This is now fixed in the fixing_440 branch

**Comment by stevenrbrandt** [comment]
This has been re-fixed in branch fixing_440

**Comment by hkaiser** [comment]
I believe we can close this now. Please re-open, if necessary.
