### ISSUE TITLE
Blaze error during compilation on KNL

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#457]
Getting this error from blaze when building on KNL, will also follow up with the blaze folks:

```
/home/buildbot/slaves/phylanx/knl-gcc7-release/build/tools/buildbot/src/blaze-head/blaze/math/simd/Equality.h: In function ‘bool blaze::equal(const blaze::SIMDfloat&, const blaze::SIMDfloat&)’:
/home/buildbot/slaves/phylanx/knl-gcc7-release/build/tools/buildbot/src/blaze-head/blaze/math/simd/Equality.h:523:14: error: there are no arguments to ‘_mm512_cmple_ps_mask’ that depend on a template parameter, so a declaration of ‘_mm512_cmple_ps_mask’ must be available [-fpermissive]
       return _mm512_cmple_ps_mask( xmm1, xmm2 ) == 0xffff;
              ^~~~~~~~~~~~~~~~~~~~
```

**Comment by khuck** [comment]
Also posted to the Blaze developers:
https://bitbucket.org/blaze-lib/blaze/issues/167/error-building-on-intel-knl

**Comment by khuck** [comment]
According to Klaus, a number of Intel intrinsics are missing in the GCC compiler implementation...

**Comment by hkaiser** [comment]
@khuck: Would a newer gcc help with this?

**Comment by khuck** [comment]
@hkaiser I have no idea.  The Blast team is looking into a workaround.

**Comment by khuck** [comment]
The Blaze team had to make a number of modifications to deal with the fact that GNU has missing intrinsics.  Unfortunately, there is one bug in the GNU intrinsics that will now compile but has a performance impact.  We will have to remember that this is a known performance issue on KNL, unless Phylanx is compiled with Intel or Clang.  From Klaus:

```
We also encountered this compilation issue, but identified it as another serious bug in GCC. The function signature as shown by the compiler (__m512d _mm512_abs_pd(__m512) indicates that GCC is using the wrong argument type (it should be __m512d instead of __m512).
...
Commit 5aa4175 resolves the issue by disabling the AVX512 abs() overload for double. You will be able to compile and to use abs(), but the operation will not be vectorized. In other words, we treat the _mm512_abs_pd() intrinsic as non-existent. 
```
