### ISSUE TITLE
Handling HPX configurations in Python

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#469]
This is based on @ct-clmsn suggestion in PR #461.

HPX run-time should be made configurable in Python. Currently, as @hkaiser explains in the same PR, HPX is initialized with parameters set during the compilation of Phylanx when `phylanx` module is loaded.

**Comment by hkaiser** [comment]
@rtohid Wasn't this fixed by #566? Can we close this now?

**Comment by hkaiser** [comment]
This has been fixed by merging #675
