### ISSUE TITLE
Allow for np.arrays()s to be usable with map()/parallel_map()

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#472]
We should add support for iterating over the elements of np.array()'s using `map()` and `parallel_map()`.

**Comment by stevenrbrandt** [comment]
I thought you said you didn't want to do this?

**Comment by hkaiser** [comment]
Well, the overwhelming number of requests forced the issue ;-)
Also, I'm working on this, should be available soonish.

**Comment by hkaiser** [comment]
This was resolved by #476.
