### ISSUE TITLE
phylanx aborts with get/set primitive in loops

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#480]
phylanx prints/sets value in 2 iterations over the loop inside `print_mat` before aborting execution.

```
import phylanx
from phylanx.ast import *
import numpy as np

@Phylanx
def print_mat(w, wlen):
    print(wlen)
    for i in range(wlen):
        print((i, w[i])
        w[i] = i

if __name__ == "__main__":
    w = np.zeros(100)
    wlen = w.shape[0]

    for i in range(wlen):
        print( (i, w[i])

    print_mat(w, wlen)
```

**Comment by ct-clmsn** [comment]
oh, any advice on how to debug these types of errors or provide better debugging comments would be appreciated!

**Comment by stevenrbrandt** [comment]
@ct-clmsn @hkaiser The above code runs for me without error on the latest Phylanx (well, after fixing the syntax errors with the unclosed parenthesis).

**Comment by hkaiser** [comment]
@ct-clmsn this is most probably the GIL problem we have somewhere in the `cout` primitive. I'll try to fix this asap, it's a pain for everybody.

**Comment by hkaiser** [comment]
> oh, any advice on how to debug these types of errors or provide better debugging comments would be appreciated!

@ct-clmsn I wish I knew how to debug problems related to the Python GIL. I was not able to find any information on how to do that.

**Comment by ct-clmsn** [comment]
@stevenrbrandt @hkaiser just did some fiddling around and found something interesting.

```
@Phylanx
def printloop():
    n = 0
    for i in range(10):
        n = i
        print(i)
```

this version code works just fine. when `n = i`  is commented out, everything goes sideways and i get a nondeterministic set of prints (usually between 2 and 4).

this [SO](https://stackoverflow.com/questions/651048/concurrency-are-python-extensions-written-in-c-c-affected-by-the-global-inter) post had some nice pointers to articles about the GIL and turning it off in PyC/C++ extension code. specifically this [article](http://jessenoller.com/2009/02/01/python-threads-and-the-global-interpreter-lock/) wasn't too bad.

**Comment by hkaiser** [comment]
@ct-clmsn removing the assignment makes it work only coincidentally. Things really depend on what kernel thread the `print` ends up being executed and having different pieces of work in flight might change things, even more as tasks (HPX threads) might get stolen by the HPX schedulers and may end up running on any of the kernel threads.

My current assumption is that pybind handles the GIL properly and everything works fine as long a `print` ends up being executed on a kernel thread that was used to run the GIL related thread initialization in pybind. Not all kernel threads however run the pybind11 (Python->C++) transition code and running `print` on a kernel thread that didn't run that code will makes things blow up.

**Comment by hkaiser** [comment]
We most probably need to find a way to introduce the threads created by the HPX runtime to Python. The GIL related thread state is stored in a thread-local variable which needs to be properly initialized to avoid the problems we're seeing. There exists a Python API for this (which is also used by pybind). The question is how to tie that into HPX.

**Comment by stevenrbrandt** [comment]
This complex thread seems related to the issues we're having https://github.com/pybind/pybind11/issues/1360 here. Not quite sure if it contains a fix, mostly I'm posting the link so I don't lose it.

**Comment by ct-clmsn** [comment]
@stevenrbrandt @hkaiser this [link](http://pybind11.readthedocs.io/en/stable/advanced/pycpp/utilities.html) helped clarify the underlying issue with print. As of today, this set/get issue is resolved. I'll close the ticket! thanks!

**Comment by stevenrbrandt** [comment]
@ct-clmsn how did you resolve it? Is there a pull request somewhere?

**Comment by ct-clmsn** [comment]
@stevenrbrandt needed to modify my unit testing process. did a source update with recompile on hpx and phylanx and suddenly all was good. i'll be adding source updates with recompiles to my bug assessment checklist.

**Comment by stevenrbrandt** [comment]
@ct-clmsn do you get this error on shutdown? I get it all the time
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  scoped_acquire::dec_ref(): thread state must be current!
Aborted (core dumped)
```

**Comment by ct-clmsn** [comment]
@stevenrbrandt not yet; just 'Aborted'.

**Comment by hkaiser** [comment]
> @stevenrbrandt not yet; just 'Aborted'.

@ct-clmsn the diagnostic message Steve is seeing is printed in Debug mode only (see https://github.com/pybind/pybind11/blob/master/include/pybind11/pybind11.h#L1815-L1820)

**Comment by hkaiser** [comment]
@stevenrbrandt Could you get me a stack backtrace for this abort, please?
