### ISSUE TITLE
error updating function parameter values

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#482]
hit an issue running the following code
```
import phylanx
from phylanx.ast import *

import numpy as np

@Phylanx
def runtwo(x):
    x = x
    # any of the following produces the same error
    # x += x
    # x = x + x
    # x = x + 1
    # x += 1

@Phylanx
def run():
    W = 100
    T = 4
    a_1 = constant(0.0, make_list(W, T))
    a_2 = constant(0.0, make_list(W, T))
    cout(a_1)
    runtwo(a_1)
    cout(a_1)
    cout(a_2)
    runtwo(a_2)
    cout(a_2)
```
if the code is placed into a file python throws an exception on line 11. the python stack trace claims the error is in phylanx/ast/transformation.py  line 652. the phylanx back end throws a runtime error:

```
<unknown>: access-argument$0$x/0$7$4:: store function should only be called for the primitives that support it (e.g. variables): HPX(invalid_status)
```

**Comment by stevenrbrandt** [comment]
Actually, you can get the same error with this
```
from phylanx.ast import *

@Phylanx(debug=True)
def runtwo(x):
    x = x

runtwo(3)
```

**Comment by ct-clmsn** [comment]
@stevenrbrandt savage!

**Comment by hkaiser** [comment]
This is a know issue. You can't re-assign a value to a function argument. @stevenrbrandt perhaps we should copy all function arguments into (function-) local variables in the generated PhySL code.

**Comment by stevenrbrandt** [comment]
@hkaiser it depends on what you mean by "copy." The code below should still print out [0,2,0]
```
from phylanx.ast import Phylanx

@Phylanx
def foo(a):
	a[1] = 2

@Phylanx
def bar():
	b = hstack(0,0,0)
	foo(b)
	print(b)

bar()
```

**Comment by stevenrbrandt** [comment]
It's worse... you can't even print an argument now.
```
from phylanx.ast import Phylanx

@Phylanx(debug=True)
def foo(a):
	print("a=",a)

foo()
```

**Comment by hkaiser** [comment]
@stevenrbrandt did you mean to comment on a different ticket?

**Comment by hkaiser** [comment]
> @hkaiser it depends on what you mean by "copy." The code below should still print out [0,2,0]

@stevenrbrandt PhySL has no variable references.

**Comment by hkaiser** [comment]
This looks like a duplicate to #540, closing...
