### ISSUE TITLE
Variables PhySL functions are written to only once

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#491]
Variables inside PhySL functions get their value the first time `define` is evaluated.

e.g.
```scheme
define(f, a, block(
    define(b, a),
    cout(a),
    cout(b),
    0
))
f(1)
f(2)
```
Output:
```
1
1
2
1
```

**Comment by hkaiser** [comment]
Yes, this is one of the know idiosyncrasies of the current compiler implementation where variables are handled differently form functions. I hope to have a solution for this soon.

**Comment by weilewei** [comment]
Thanks! Hope it can be solved soon.

**Comment by hkaiser** [comment]
This has been fixed on the fixing_compiler branch (https://github.com/STEllAR-GROUP/phylanx/tree/fixing_compiler).
