### ISSUE TITLE
Empty list defined inside Phylanx function has an issues 

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#509]
Empty list defined inside Phylanx function can automatically append the input list of the function. 
For example,
code
```
from phylanx.ast import *
import numpy as np


@Phylanx(debug=True)
def testing_list(a):
    b = []
    print(b)


a = [4, 3, 2, 1]
testing_list(a)
```
yields
```
define(
    testing_list,
    a,
    block(
        define(
            b,
            make_list()
        ),
        (
            cout(b)
        )
    )
)
make_list(make_list(4, 3, 2, 1))
```

**Comment by hkaiser** [comment]
@weilewei What is the expected output of the snippet above, and what do you see actually?

**Comment by weilewei** [comment]
@hkaiser First, I create an empty list inside the function and want to print this empty list. But what the PhySL prints is not an empty list, but a list that copied the value of the last parameter.

**Comment by weilewei** [comment]
I expect `[]` to be returned by the following function:
```py
@Phylanx
def test_empty_list(a, b):
    c = []
    return c


a = [1, 2, 3]
b = [4, 5]
c = test_empty_list(a, b)
print(c)
```
however, it returns
```
[[1, 2, 3], [4, 5]]
```
which is the `make_list` of all the function's input arguments. Therefore, the following test fails
```py
@Phylanx
def test_empty_list(a, b):
    c = []
    return c


a = [1, 2, 3]
b = [4, 5]
c = test_empty_list(a, b)
assert (c == [])
```

**Comment by hkaiser** [comment]
@weilewei this has been fixed for the new compiler (here: https://github.com/STEllAR-GROUP/phylanx/tree/fixing_compiler).

**Comment by weilewei** [comment]
Thank you! @hkaiser

**Comment by hkaiser** [comment]
@weilewei while other tests are still failing on that branch, this particular issue was fixed (https://circleci.com/gh/STEllAR-GROUP/phylanx/5075)
