### ISSUE TITLE
Empty np.array defined inside Phylanx function has an issues

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#510]
Similar to #509 but this time it is numpy array.
Empty np.array defined inside Phylanx function can automatically append the input np.array of the function.
For example,
code
```py
from phylanx.ast import *
import numpy as np


@Phylanx(debug=True)
def testing_array(a):
    b = np.array([])
    print(b)


a = np.array([4, 3, 2, 1])
testing_array(a)
```
yields,
```
define(
    testing_array,
    a,
    block(
        define(
            b,
            hstack()
        ),
        (
            cout(b)
        )
    )
)
[4, 3, 2, 1]
```

But if you put `b = np.array([1])`, the result is correct.

**Comment by hkaiser** [comment]
@weilewei What is the expected output and what do you actually see?

**Comment by weilewei** [comment]
@hkaiser First, I create an empty array inside the function and want to print this empty array. But what the PhySL prints is not an empty array, but an array that copied the value of the last parameter.

**Comment by hkaiser** [comment]
I understand that. Could you please document literally the expected and real outputs for the code above? Better yet, rewrite the code snippet as a test?

**Comment by weilewei** [comment]
I expect `[]`  to be returned by the following fucntion:
```py
@Phylanx
def test_empty_array_1(a, b):
    c = np.array([])
    return c


a = np.array([1, 2, 3])
b = np.array([4, 5])
c = test_empty_array_1(a, b)
print(c)
```
however, it returns,
```
[1. 2. 3. 4. 5.]
```
which is the `hstack` of all the function's input arguments. Therefore, the following test fails
```py
from phylanx.ast import *
import numpy as np


@Phylanx
def test_empty_array_1(a, b):
    c = np.array([])
    return c


a = np.array([1, 2, 3])
b = np.array([4, 5])
c = test_empty_array_1(a, b)
assert (c.size == 0)
```

**Comment by hkaiser** [comment]
@weilewei This has been fixed for the new compiler (here: https://github.com/STEllAR-GROUP/phylanx/tree/fixing_compiler).

**Comment by weilewei** [comment]
Thanks! @hkaiser

**Comment by weilewei** [comment]
@hkaiser I run the test on the branch of fixing_compiler just now but the test failed. Shall I wait for a while?
