### ISSUE TITLE
Local variable remained unchanged after the 1st time calling the fucntion

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#512]
I expect 
```
1
2
```
to be returend by the following function
```py
from phylanx.ast import *
import numpy as np


@Phylanx
def foo1(x):
    local_x = x
    return local_x

c = 1
d = 2
print(foo1(c))
print(foo1(d))
```
however, it returns
```
1
1
```
Therefore, the following test fails
```py
@Phylanx
def foo1(x):
    local_x = x
    return local_x

c = 1
d = 2

assert (foo1(c) == 1)
assert (foo1(d) == 2)
```

**Comment by weilewei** [comment]
@hkaiser oh, thanks! I will check it out.

**Comment by weilewei** [comment]
@hkaiser 
The issue still persists if a new value is assigned to a local variable. For example, in the following code,
we expect `2` for both invocations of the function `foo`, but we get `2` and `3` respectively for the 1st and 2nd invocations with the same argument `1`.

```py
@Phylanx
def foo(x):
    local_x = x
    local_x = local_x + 1
    print(local_x)


print(foo(1))
print(foo(1))
```

Therefore, the following test failed:
```py
@Phylanx
def foo(x):
    local_x = x
    local_x = local_x + 1
    return local_x


assert 2 == foo(1)
assert 2 == foo(1)
```

**Comment by weilewei** [comment]
@hkaiser with branch `fixing_compiler` and its `commit a1b31fd94e7ab85f52062daf36efc308d8d8faf7` and `Date:   Mon Jul 9 11:45:56 2018 -0500`

**Comment by hkaiser** [comment]
@weilewei this should be fixed now (on that branch). Thanks!

**Comment by weilewei** [comment]
@hkaiser Thank you so much! It works!
