### ISSUE TITLE
Multi-dimension np.array cannot be created in Phylanx

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#522]
I expect the following code works
```py
@Phylanx
def foo():
    x = np.array([[1, 1]])
    return x


a = foo()
```
However, it complains
```py
RuntimeError: <unknown>(6, 8): hstack:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ir::range'): HPX(bad_parameter)
```
However, one dimensional np.array works fine inside the Phylanx. For example, if you change `x` to `np.array([1, 1])`

One potential testing code could be as follows (I am unsure if it helps)
```py
@Phylanx
def foo():
    x = np.array([[1, 1]])
    return x


a = foo()
v = np.array([[1, 1]]) == foo()
assert (True == v.any())
```

**Comment by hkaiser** [comment]
@weilewei The code above is translated to this PhySL:
```
define(
    foo,
    block(
        define(
            x,
            hstack(
                make_list(1, 1)
            )
        ),
        x
    )
)
```
which doesn't look right to me. This the probable reason for the error message you're seeing. @rtohid do you think this could be changed in the frontend? I think this should use `hstack` instead of the `make_list`, which would produce the correct array type.

**Comment by hkaiser** [comment]
I'm going to add support to `hstack` and `vstack` to accept lists as inner arguments. However the snippet above should be translated to:
```
define(
    foo,
    block(
        define(
            x,
            vstack(                 # <-- note here
                make_list(1, 1)
            )
        ),
        x
    )
)
```
as the inner arrays have to be interpreted as rows of the produced column, not columns.
