### ISSUE TITLE
Unexpected slicing issue

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#527]
I did not expect the following code works, but it prints `3`. However, in pure Python (without `@Phylanx(debug=True)`), it returns `TypeError: 'int' object is not subscriptable`.

```py
@Phylanx(debug=True)
def foo(x):
    print(x[2])

foo(3)
```
FYI, I attached PhySL code as follows
```
define(
    foo,
    x,
    (
        cout(
            slice(x,2)
        )
    )
)
```

**Comment by hkaiser** [comment]
Is this still a problem?

**Comment by hkaiser** [comment]
@weilewei on current master I see:
```
RuntimeError: D:\Devel\phylanx\tests\regressions\python\527_slicing.py(5, 10): slice:: cannot extract anything but the first element from a scalar: HPX(bad_parameter)
```
I think this addresses your issue. Closing...
