### ISSUE TITLE
Python frontend should pass filename

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#539]
The Python frontend should pass along the name of the Python file executed to the backend to improve error messages.

**Comment by hkaiser** [comment]
@rtohid what is the status of this?

**Comment by rtohid** [comment]
@hkaiser The easy part of extracting the file's name is done. I still need to look into the C++ side and figure out what needs to be exposed to Python. I assume it should be an extra argument to `execution_tree.eval`, is that correct? Thanks.

**Comment by hkaiser** [comment]
The source name needs to end up as an (additional) first argument to `compile` here: https://github.com/STEllAR-GROUP/phylanx/blob/master/python/src/bindings/binding_helpers.hpp#L163.
