### ISSUE TITLE
primitives request: count_nonzero and nonzero

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#546]
request for a new primitive that implements [numpy.count_nonzero](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.count_nonzero.html) and a primitive for [numpy.nonzero](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nonzero.html)

**Comment by hkaiser** [comment]
Note: `numpy.nonzero` is equivalent to `numpy.where` with just one argument (see #551).
