### ISSUE TITLE
primitive request: numpy.arange

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#553]
provide [numpy.arange](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.arange.html#numpy.arange) support.

**Comment by hkaiser** [comment]
What's the difference to the (existing) `linspace()` primitive (https://github.com/STEllAR-GROUP/phylanx/wiki/linspace-Primitive)?

**Comment by stevenrbrandt** [comment]
@hkaiser, both functions exist in numpy and are similar
arange(start,end,step_size)
linspace(start,end,num_steps)
Also, arange() defaults to integer type while linspace to real. Thus, arange(0,4,1,dtype=float) gives the same answer as linspace(0,3,4).

**Comment by hkaiser** [comment]
Can we do the mapping in the frontend without having to create YAP (yet another primitive)? @rtohid?

**Comment by ct-clmsn** [comment]
@hkaiser @stevenrbrandt forgot we had linspace! (I should RTM) The difference between them is subtle. you can replicate an arange over floats using linspace and a floor operation. speaking of which...do we have a floor/ceil primitive?

**Comment by hkaiser** [comment]
@ct-clmsn we do have `floor` and `ceil`, see: https://github.com/STEllAR-GROUP/phylanx/wiki/Unary-Math-Operations

**Comment by hkaiser** [comment]
@ct-clmsn also, you might be able to get away without `floor` or `ceil':
```
>>> linspace(0, 10, 11)
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])  
```

**Comment by ct-clmsn** [comment]
@hkaiser excellent! revisiting the documentation! (I've become the bofh) 8| 

For the situation you described, would the backend re-interpret the double precision values as ints if the linspace values are used for indexing?

**Comment by hkaiser** [comment]
> For the situation you described, would the backend re-interpret the double precision values as ints if the linspace values are used for indexing?

@ct-clmsn it was merely a question. I'm not sure if it's feasible. The numpy guys implemented both for a reason, after all.

**Comment by stevenrbrandt** [comment]
One issue here is the "dtype=32". Currently, AFAIK, PhySL has no way of supporting that syntax.

**Comment by hkaiser** [comment]
PhySL should derive the type used for the generated list of values from the arguments. We have only recently started to consistently apply this to the primitives. `linspace` might still be blindly generating arrays of doubles at this point. I'll investigate.

**Comment by ct-clmsn** [comment]
@hkaiser should this ticket be closed?

**Comment by hkaiser** [comment]
@ct-clmsn let's leave it open, I plan to expose `arange` from the `linspace` primitive, shouldn't be too hard.

**Comment by hkaiser** [comment]
> would it be an over-simplification to make arange an integer version of linspace?

@ct-clmsn the arguments of `arange` and `linspace` have slightly a different meaning. I'm not sure yet how much these two can be unified using the same implementation basis. In any case, even a completely separate `arange` shouldn't incur too much work.

Also, for the integer version of `arange` we might be able to borrow or reuse the existing code we have for `range`.

**Comment by stevenrbrandt** [comment]
@hkaiser while using the type of the arguments to arange() to deduce whether to generate integer or real matches the behavior of Python, doing so for linspace() is diffferent from Python.

**Comment by stevenrbrandt** [comment]
@hkaiser if functions could return their list of argument names, and arguments could have default values, this could work.
