### ISSUE TITLE
Setup buildbot environment for regular regression testing

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#6]
Set up a buildbot system at UO for building HPX, APEX, Phylanx and executing tests.

Systems:
* x86_64 linux  delphi.nic.uoregon.edu
  - gcc
* Power8 Linux  (minotaur,centaur).nic.uoregon.edu
  - xlc, clang?
* KNL Linux  grover.nic.uoregon.edu
  - gcc
  - intel
* Windows, if possible   (Monil's machine)
  - msvc

The buildbot master configurations will be as simple as possible, and most of the complexity will reside in scripts that are in the Phylanx repository. That way, the configure/build/test cycle can be executed outside of the buildbot environment for fixing failed tests.

For portability (i.e. windows support), should be scripts be in Python instead of bash?  Or does Windows support bash scripting (do we require the windows subsystem for linux)?

The build support will include the ability to specify the git branch for each of HPX, APEX, Phylanx.

Todo:
- [x] set up buildbot service on ktau (allows external clients to connect)
- [x] install buildbot clients on delphi, centaur, grover, windows
- [x] basic script for x86_64 linux
- [x] port to knl
- [x] port to power8
- [x] port to windows (covered by AppVeyor)

**Comment by hkaiser** [comment]
@khuck: can this be closed now?
