### ISSUE TITLE
Branch 'advanced_indexing': Boolean mask in Python is broken.

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#620]
Running:
```py
from phylanx import Phylanx
import numpy as np


@Phylanx
def foo():
    x = np.array([2, 0, 1, 1])
    b = np.array([True, True, False, False])
    return x[b]

assert (foo() == np.array([2, 0])).all
print(foo())
```
causes the following error:
```
RuntimeError: <unknown>: unexpected type for indices used for advanced integer array indexing: HPX(bad_parameter)
```

Expected output is `[2 0]`

**Comment by hkaiser** [comment]
@rtohid I'm not able to reproduce this problem. For me your test produces `[2 0]` as expected. I have tested with https://github.com/STEllAR-GROUP/phylanx/commit/ee6ec293a96257b2d92f5f7e3ddeedf906a3c4e0.

**Comment by rtohid** [comment]
@hkaiser My mistake, it works for me too- I was working with an older commit.
