### ISSUE TITLE
parallel_block in physl does not make fibonacci possible

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#647]
The following Fibonacci code essentially prints random numbers. It appears that there is no wait at the end of the parallel block.
```scheme
block(
    define(fib, n, block(
        define(r, 0),
        if(n < 2,
            store(r, n),
            if(n < 5,
                store(r, fib(n-1)+ fib(n-2)),
                block(
                    define(f1, 0),
                    define(f2, 0),
                    parallel_block(
                        store(f1, fib(n-1)),
                        store(f2, fib(n-2))
                    ),
                    store(r, f1 + f2)
                )
            )
        ),
        r
    )),
    for_each(lambda(i,
        cout(i, fib(i))
    ),
        range(1, 10)
    )
)
```

**Comment by stevenrbrandt** [comment]
On further investigation, this problem may not have anything to do with parallel blocks. The following fib function also produces wrong answers:
```
@Phylanx(debug=True)
def fib3(n):
    r = 0 
    if n < 2:
        r = n 
    else:
        f1 = fib3(n-1)
        f2 = fib3(n-2)
        r = f1 + f2
    return r
```
Apparently, the variables used in the body of the program are not behaving as expected. I thought this issue was fixed a while back.

**Comment by hkaiser** [comment]
Yes, this might be the same problem as reported here: #364. I think I understand what's causing this, but I have no immediate solution nor workaround for now.
