### ISSUE TITLE
should function return ir::node_data<T>?

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#709]
https://github.com/STEllAR-GROUP/phylanx/blob/2ce63efb322a5b01ed8b32dc837f060cd76e8374/phylanx/execution_tree/primitives/node_data_helpers.hpp#L1059

found a small compilation issue with gcc on this line.

**Comment by hkaiser** [comment]
@ct-clmsn yes, thanks. this is a bug. Will fix.

**Comment by hkaiser** [comment]
@ct-clmsn please see #711 for a fix.
