### ISSUE TITLE
Phylanx installer always creates /cmake/Phylanx

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#716]
This issue can be reproduced by installing Phylanx into any directory (i.e. An attempt to create `/cmake/Phylanx` will be made regardless of the destination directory).

To reproduce on [`stellargroup/phylanx_base:prerequisites`](https://hub.docker.com/r/stellargroup/phylanx_base/) Docker image (e.g. `docker run -it stellargroup/phylanx_base:prerequisites`) run the following commands:

```sh
git clone https://github.com/STEllAR-GROUP/phylanx --branch=master --depth=1 /phylanx
cmake -H/phylanx -B/build -DHPX_DIR=/usr/local/lib/cmake/HPX -Dblaze_DIR=/blaze/share/blaze/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -G Ninja
cmake --build /build
cmake --build /build --target install
```

**Comment by ct-clmsn** [comment]
@parsa nice catch! I've been having the same issue working on the randomforest code.

**Comment by stevenrbrandt** [comment]
Adding this one line seems to fix the problem
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 46081e89..50ceb128 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -31,6 +31,7 @@ set(PHYLANX_VERSION "${PHYLANX_MAJOR_VERSION}.${PHYLANX_MINOR_VERSION}.${PHYLANX
 set(PHYLANX_LIBRARY_VERSION "${PHYLANX_VERSION}")
 set(PHYLANX_SOVERSION ${PHYLANX_MAJOR_VERSION})
 set(PHYLANX_PACKAGE_NAME Phylanx)
+set(LIB ${CMAKE_INSTALL_PREFIX})
 
 set_property(GLOBAL PROPERTY USE_FOLDERS ON)
 
```

**Comment by hkaiser** [comment]
We should use `${CMAKE_INSTALL_LIBDIR}` instead of `LIB`. There are other places that could benefit from using the various existing CMAKE directory variables.
