### ISSUE TITLE
physl plugin support features

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#722]
Please add the following to the physl interpreter:

1) Add flag: ``--ls-plugins`` which shows:
* the directories(y) checked for plugins
* plugins discovered at runtime/startup; in the absence of code to run, the flag causes a print out of the plugins discovered

2) Add flag: ``--help-primitive=`` which accepts a PhySL function/primitive string name (example: 'eye') as an argument. the command returns:
* the full path and name of the plugin shared object the primitive belongs to (the so or dll file)
* the 'help' string of the primitive
* if the primitive is not found, print '%s not found' ('%s' is the physl function/primitive queried) and the path(s) searched for plugins

3) Add environment variable for finding plugins installed to a non-standard directory:
* ``$PHYSL_PLUGINS_DIRS``
* The envvar is a ':' delimited list of directories to search for plugins at interpreter startup.

**Comment by hkaiser** [comment]
@stevenrbrandt Is that something you could work on? I can implement the `$PHYSL_PLUGINS_DIRS` custom load directory option as it requires changes to HPX).
