### ISSUE TITLE
lra_csv_instrumented doesn't output performance data

### ISSUE THREAD

**Issue by kawilliams** [STEllAR-GROUP/phylanx#746]
In phylanx/build/bin, lra_csv_instrumented doesn't output any of the performance information (Newick tree, performance csv, etc), it only outputs the numeric solution. 

In contrast, phylanx/build/bin/als_csv_instrumented has the proper behavior and outputs performance data. I would like to use both als and lra to collect performance data for comparative trees. Thank you!

**Comment by scheherzade** [comment]
Hey Katy,  I just tried it and it works for me. Could you please paste the exact command line that you used?
The gist of me trying it is located here:
https://gist.github.com/scheherzade/5f5c59ae765ce31f925f93b6448d29f2

**Comment by kawilliams** [comment]
I have not been using the --instrument flag. I had been running like this:
srun -n 1 ./als_csv_instrumented --data_csv=../../examples/algorithms/datasets/MovieLens.csv -t2 > output

And somehow I had been getting the correct output for all builds until now (I have the saved output files). I tried to replicate it now and no longer get the performance data with the output. 

I tested the command you used in the gist and I get the expected behavior so I will use that from now on:
./lra_csv_instrumented --data_csv=../../examples/algorithms/datasets/breast_cancer.csv 
**Gives the result only**

./lra_csv_instrumented --data_csv=../../examples/algorithms/datasets/breast_cancer.csv --instrument
**Gives the full output (result & performance data)**

./als_csv_instrumented --data_csv=../../examples/algorithms/datasets/MovieLens.csv
**Gives the result only **

 ./als_csv_instrumented --data_csv=../../examples/algorithms/datasets/MovieLens.csv --instrument
**Gives me the full output**

Thank you!

**Comment by hkaiser** [comment]
@kawilliams can we close this now? Or is there anything else related you would like to se being implemented?

**Comment by kawilliams** [comment]
We're good, thanks.

**Comment by alex-r-bigelow** [comment]
I think I've run into the same problem (continuing the discussion from https://github.com/khuck/xpress-apex/issues/98). I'm running this script:

```bash
#!/bin/bash
export TARGET_DIR="/home/abigelow/build-1548790457"
module load clang/6.0.1
module load cmake/3.9.0
module load gperftools/2.7
module load boost/1.68.0-clang6.0.1-debug
module load hwloc/2.0.0
module load papi/5.6.0
module load blaze/3.4
module load pybind11/2.2.4
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TARGET_DIR/hpx/lib:$TARGET_DIR/hpx/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TARGET_DIR/phylanx/lib:$TARGET_DIR/phylanx/lib64
export APEX_OTF2=1

srun -n 1 -t 2 \
  $TARGET_DIR/phylanx/bin/als_csv_instrumented \
  --data_csv=$HOME/MovieLens.csv > output.txt
```

Trying `--instrumented`, `--dump-newick-tree=tree.txt`, `--dump-counters=performance.txt` all give me an `unrecognised option` error

**Comment by justwagle** [comment]
I think you need to pass --instrument.

**Comment by alex-r-bigelow** [comment]
That was it. 😳 Thanks!
