### ISSUE TITLE
tests.unit.plugins.booleans.where_operation times out with Debug build

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#777]
one buildbot failure with the Debug configuration - tests.unit.plugins.booleans.where_operation will time out after 100 seconds.  This is with hpx, boost and phylanx all built with Debug.  Every other test finishes in time.  tests.unit.execution_tree.generate_tree also takes at least 96 seconds.  Most other tests are less than 10 seconds, some are between 10 and 40 seconds.  Should we increase the timeout for Debug build tests?  In isolation, it takes ~135 seconds to run.

**Comment by hkaiser** [comment]
@khuck could you increase the timeout? Alternatively I could split the where_operation tests into smaller pieces.
