### ISSUE TITLE
Add BLAS support

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#79]
BLAS is required by some Blaze functions we use in Phylanx. e.g. [matrix inversion](https://bitbucket.org/blaze-lib/blaze/wiki/Matrix%20Operations#!matrix-inversion) and [matrix determinant](https://bitbucket.org/blaze-lib/blaze/wiki/Matrix%20Operations#!det)

Needs CMake support.

**Comment by ct-clmsn** [comment]
@parsa @hkaiser would the existing [HPX blas infrastructure](https://github.com/STEllAR-GROUP/hpxla) be worth revisiting?

**Comment by hkaiser** [comment]
@ct-clmsn interesting idea. Please understand however that this was never a) verified to properly work, nor b) never optimized for performance. But as a fallback this might be something to look into. Thanks for reminding me of this work - I had completely forgotten that it existed.

**Comment by ct-clmsn** [comment]
@hkaiser could blaze (or an hpx-integrated blaze) fit into it as a matrix-template type?

**Comment by hkaiser** [comment]
This has been fixed by merging #88.
