### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#810]
It takes a long time to run the tests. The machine I typically run on has 40 cores (80 hyperthreads). It would be nice if I could use this parallelism to get through the testsuite faster.

**Comment by khuck** [comment]
I would definitely endorse this

**Comment by hkaiser** [comment]
@stevenrbrandt Wouldn't using the `-j` flag in the `make tests` do the trick?

**Comment by khuck** [comment]
@hkaiser it builds the tests in parallel, but then cmake runs them serial.

**Comment by khuck** [comment]
@hkaiser @stevenrbrandt you can set the CTEST_PARALLEL_LEVEL environment variable before running the test: 
https://cmake.org/cmake/help/v3.12/manual/ctest.1.html

**Comment by stevenrbrandt** [comment]
@khuck interesting

**Comment by khuck** [comment]
@stevenrbrandt @hkaiser I tried it out on the Phylanx build - the tests were run concurrently, but it made all the tests run 10-60x slower.  Why?

**Comment by hkaiser** [comment]
@khuck HPX binds threads to cores. As the concurrently running tests don't know anything about each other all of them bind their threads to the same cores. That puts all the burden of multiplexing things on those cores on the OS....

**Comment by khuck** [comment]
@hkaiser ah, of course.

**Comment by stevenrbrandt** [comment]
@khuck @hkaiser so what we need is some way to figure this out. Maybe if 
CTEST_PARALLEL_LEVEL is set we could disable the core bindings or do some other intelligent thing?

**Comment by khuck** [comment]
Is there an HPX argument that tells it not to pin threads?  If so, we could use that.  The other problem is that we can detect that CTEST_PARALLEL_LEVEL has been set, but we can't detect if someone calls "ctest -j ..."

**Comment by hkaiser** [comment]
@khuck: good point. `--hpx:bind=none` should do what you're asking for (no thread binding).

**Comment by stevenrbrandt** [comment]
@hkaiser @khuck so that's an argument that has to be passed to the tests when they are invoked. That's going to be tricky to add to make files, integrate with the python libraries, etc. Can that be set with an environment variable?

**Comment by hkaiser** [comment]
@stevenrbrandt I have created an HPX ticket asking for this functionality as it is not available at this point (see https://github.com/STEllAR-GROUP/hpx/issues/3724).

**Comment by hkaiser** [comment]
@khuck, @stevenrbrandt: https://github.com/STEllAR-GROUP/hpx/pull/3726 has been merged. You should now be able to set the environment variable `HPX_COMMANDLINE_OPTIONS=--hpx:bind=none` to achieve what you need.

**Comment by hkaiser** [comment]
@khuck, @stevenrbrandt can we close this?

**Comment by khuck** [comment]
@hkaiser yep

**Comment by stevenrbrandt** [comment]
I believe so. My tests ran in just over 22 sec.
