### ISSUE TITLE
blaze::ravel dne?

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#811]
i'm getting a build error on the following function call: blaze::ravel; not sure if blaze has a ravel function. a quick fgrep over the blaze source tree didn't identify one.

**Comment by khuck** [comment]
@ct-clmsn Are you including the blaze tensor library?  That's a recent addition that I just learned about.  It's supposed to be optional, but not all code locations are fenced off with ```#ifdef``` checks.

You'll need to:

```
    git clone https://github.com/STEllAR-GROUP/blaze_tensor.git
    mkdir build && cd build
    cmake \
    -DCMAKE_CXX_COMPILER=`which ${mycxx}` \
    -DCMAKE_C_COMPILER=`which ${mycc}` \
    -DCMAKE_BUILD_TYPE=${buildtype} \
    -Dblaze_DIR=${blaze_build_dir}/share/blaze/cmake \
    -DHPX_DIR=${HPX_ROOT}/lib/cmake/HPX \
    -DCMAKE_INSTALL_PREFIX=. \
    ${blazetensor_src_dir}
    make -j && make install
```

Then include blaze tensor in the phylanx build (it may help to export BlazeTensor_DIR in your environment, too):

```
    -DBlazeTensor_DIR=${BlazeTensor_DIR}
```

**Comment by ct-clmsn** [comment]
@hkuck doah!

**Comment by kisaacs** [comment]
I'm running into this problem now, both with blaze::ravel and with blaze::mean in the keras_support plugin. I tried adding `-DBlazeTensor_DIR` to my cmake line and got a cmake warning that it's not used anymore:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    BlazeTensor_DIR
```

I'm using the rostam modules blaze/3.5 and blaze-tensor/master but maybe I need to be building blaze myself. Any ideas? Thanks!

**Comment by taless474** [comment]
@kisaacs blaze::mean is added recently (2019‑06‑09) and blaze 3.5 is released a few months ago (2019-02-26). Would you please update blaze (use master) and inform me if it still happens?

**Comment by scheherzade** [comment]
@kisaacs Did you also set ```-DPHYLANX_WITH_BLAZE_TENSOR=ON```?

**Comment by kisaacs** [comment]
@scheherzade Ah, I added that and got a:
```CMake Error at cmake/Phylanx_SetupBlaze.cmake:40 (include):
  include could not find load file:

    /opt/mn/blaze-tensor/master/share/BlazeTensor/cmake/BlazeTensorConfigVersion.cmake
```

@taless474 I also tried it without blaze tensor but with blaze/master, but then I got the `blaze::mean` and `blaze::ravel` errors. Looking at the dates, it seems blaze/master is April 2, so it looks like I need to compile my own blaze and perhaps my own blaze_tensor.

**Comment by khuck** [comment]
Kate -

Here is the relevant section from the buildbot scripts, although don't understand the magic that makes Phylanx build (or not build, as the current case may be) any more, especially when it comes to blaze and blaze tensor:

 29     export CC=${mycc}
 30     export CXX=${mycxx}
 31     export FC=${myfc}
 32     export CFLAGS=${mycflags}
 33     export CXXFLAGS=${mycxxflags}
 34     #export LDFLAGS="${myldflags} ${HDF5_LDFLAGS}"
 35     export LDFLAGS=${myldflags}
 36     export blaze_DIR=${blaze_build_dir}
 37     export BlazeTensor_DIR=${blazetensor_build_dir}
 38     export HighFive_DIR=${high5_build_dir}
 39 
 40     set -x
 41     cmake \
 42     -DCMAKE_BUILD_TYPE=${buildtype} \
 43     -Dblaze_DIR=${blaze_DIR} \
 44     -DPHYLANX_WITH_BLAZE_TENSOR=ON \
 45     -DBlazeTensor_DIR=${BlazeTensor_DIR} \
 46     ${blaze_cmake_extras} \
 47     -Dpybind11_DIR=${pybind_build_dir}/share/cmake/pybind11 \
 48     -DHPX_DIR=${HPX_ROOT}/lib/cmake/HPX \
 49     -DPHYLANX_WITH_PSEUDO_DEPENDENCIES=On \
 50     -DPHYLANX_WITH_MALLOC=${malloc} \
 51     -DCMAKE_INSTALL_PREFIX=${phylanx_install_dir} \
 52     -DPYTHON_EXECUTABLE:FILEPATH=${pythonpath} \
 53     ${phylanx_src_dir}

On my gcc7.1+x86_64 linux box, ${blaze_cmake_extras} isn't set to anything.
For clang7+Power8 build, it's set to:
export blaze_cmake_extras="-DBLAS_LIBRARIES=${BLAS_DIR}/lib64/libblas.so -DLAPACK_LIBRARIES=${LAPACK_DIR}/lib64/liblapack.so"

Thanks -
Kevin

> On Jul 2, 2019, at 2:31 PM, Kate Isaacs <notifications@github.com> wrote:
> 
> I'm running into this problem now, both with blaze::ravel and with blaze::mean in the keras_support plugin. I tried adding -DBlazeTensor_DIR to my cmake line and got a cmake warning that it's not used anymore:
> 
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     BlazeTensor_DIR
> 
> I'm using the rostam modules blaze/3.5 and blaze-tensor/master but maybe I need to be building blaze myself. Any ideas? Thanks!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Kevin Huck, PhD
Research Associate / Computer Scientist
OACISS - Oregon Advanced Computing Institute for Science and Society
University of Oregon
khuck@cs.uoregon.edu
http://tau.uoregon.edu

**Comment by kisaacs** [comment]
Thanks folks. I downloaded the latest blaze and blaze_tensor with the extra option by @taless474 and that seems to have worked.
