### ISSUE TITLE
Compilation Fails

### ISSUE THREAD

**Issue by baumanfx** [STEllAR-GROUP/phylanx#812]
Compiling phylanx on a Raspberry Pi/Fedora fails with the following error:
```
[ 16%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/primitive_component_base.cpp.o
[ 16%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/slice.cpp.o
[ 18%] Building CXX object src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/slice_node_data.cpp.o
In file included from /home/a/phylanx/src/execution_tree/primitives/slice_node_data.cpp:12:
/home/a/phylanx/phylanx/execution_tree/primitives/slice_node_data_2d.hpp:269:13: error: 
      static_assert failed "sizeof(std::int64_t) == sizeof(std::size_t)"
            static_assert(sizeof(std::int64_t) == sizeof(std::size_t),
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/a/phylanx/phylanx/execution_tree/primitives/slice_node_data_2d.hpp:453:13: error: 
      static_assert failed "sizeof(std::int64_t) == sizeof(std::size_t)"
            static_assert(sizeof(std::int64_t) == sizeof(std::size_t),
            ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: *** [src/CMakeFiles/phylanx_component.dir/build.make:544: src/CMakeFiles/phylanx_component.dir/execution_tree/primitives/slice_node_data.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1133: src/CMakeFiles/phylanx_component.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```
Configuring the compilation with: -DHPX_DIR=/opt/hpx -DCMAKE_INSTALL_PREFIX=/opt/phylanx -DHPX_IGNORE_COMPILER_COMPATIBILITY=On
and calling make with -j 1.

The output of uname -a is:
```
Linux localhost 4.20.10-200.fc29.armv7hl #1 SMP Fri Feb 15 21:04:49 UTC 2019 armv7l armv7l armv7l GNU/Linux
```
CMakeFiles/CMakeError.log contains the following information:
```
Performing C++ SOURCE FILE Test HAS_FLTO failed with the following output:
Change Dir: /home/a/phylanx/build/CMakeFiles/CMakeTmp

Using clang++ version:
clang version 7.0.1 (Fedora 7.0.1-2.fc29)

Run Build Command:"/usr/bin/gmake" "cmTC_7e8a7/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_7e8a7.dir/build.make CMakeFiles/cmTC_7e8a7.dir/build
gmake[1]: Entering directory '/home/a/phylanx/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_7e8a7.dir/src.cxx.o
/usr/bin/clang++    -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-cast-align -DHAS_FLTO   -flto -o CMakeFiles/cmTC_7e8a7.dir/src.cxx.o -c /home/a/phylanx/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_7e8a7
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_7e8a7.dir/link.txt --verbose=1
/usr/bin/clang++   -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-cast-align -DHAS_FLTO   -Wl,-z,defs  -rdynamic CMakeFiles/cmTC_7e8a7.dir/src.cxx.o  -o cmTC_7e8a7 -flto 
/usr/bin/ld: BFD version 2.31.1-17.fc29 internal error, aborting at elfcode.h:224 in bfd_elf32_swap_symbol_out

/usr/bin/ld: Please report this bug.

clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_7e8a7.dir/build.make:87: cmTC_7e8a7] Error 1
gmake[1]: Leaving directory '/home/a/phylanx/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_7e8a7/fast] Error 2
```
Source file was:
int main() { return 0; }

**Comment by hkaiser** [comment]
@baumanfx please check #814 and report back if that patch fixes your issue.

**Comment by baumanfx** [comment]
After applying the 814.patch the compilation fails at a different place with this output
/opt/hpx/include/hpx/util/spinlock_pool.hpp:87:59: note: in instantiation
      of member function
      'hpx::util::spinlock_pool<hpx::naming::gid_type::tag,
      128>::spinlock_for' requested here
  ...explicit scoped_lock( void const * pv ): sp_( spinlock_for( pv ) )
                                                   ^
/opt/hpx/include/hpx/runtime/naming/name.hpp:383:46: note: in
      instantiation of member function
      'hpx::util::spinlock_pool<hpx::naming::gid_type::tag,
      128>::scoped_lock::scoped_lock' requested here
            internal_mutex_type::scoped_lock l(this);
                                             ^
In file included from /home/a/phylanx/src/plugins/matrixops/softmax_operation.cpp:8:
In file included from /home/a/phylanx/phylanx/ir/node_data.hpp:13:
In file included from /opt/hpx/include/hpx/include/serialization.hpp:10:
In file included from /opt/hpx/include/hpx/runtime/serialization/serialize.hpp:12:
In file included from /opt/hpx/include/hpx/runtime/serialization/input_archive.hpp:16:
In file included from /opt/hpx/include/hpx/runtime/serialization/input_container.hpp:12:
In file included from /opt/hpx/include/hpx/runtime/serialization/container.hpp:12:
In file included from /opt/hpx/include/hpx/runtime/naming/name.hpp:12:
In file included from /opt/hpx/include/hpx/util/spinlock_pool.hpp:23:
/opt/hpx/include/hpx/util/fibhash.hpp:50:13: warning: shift count >= width
      of type [-Wshift-count-overflow]
            >> helper::shift_amount;
            ^  ~~~~~~~~~~~~~~~~~~~~
3 warnings and 4 errors generated.
make[2]: *** [src/plugins/matrixops/CMakeFiles/matrixops_primitive.dir/build.make:492: src/plugins/matrixops/CMakeFiles/matrixops_primitive.dir/softmax_operation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2056: src/plugins/matrixops/CMakeFiles/matrixops_primitive.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

and the relevant part in the CMakeError.log:

Performing C++ SOURCE FILE Test HAS_FLTO failed with the following output:
Change Dir: /home/a/phylanx/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_2fb84/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_2fb84.dir/build.make CMakeFiles/cmTC_2fb84.dir/build
gmake[1]: Entering directory '/home/a/phylanx/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_2fb84.dir/src.cxx.o
/usr/bin/clang++    -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-cast-align -DHAS_FLTO   -flto -o CMakeFiles/cmTC_2fb84.dir/src.cxx.o -c /home/a/phylanx/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_2fb84
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2fb84.dir/link.txt --verbose=1
/usr/bin/clang++   -fdiagnostics-show-option -Werror=vla -Werror=return-type -Wno-cast-align -DHAS_FLTO   -Wl,-z,defs  -rdynamic CMakeFiles/cmTC_2fb84.dir/src.cxx.o  -o cmTC_2fb84 -flto 
/usr/bin/ld: BFD version 2.31.1-17.fc29 internal error, aborting at elfcode.h:224 in bfd_elf32_swap_symbol_out

/usr/bin/ld: Please report this bug.

clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_2fb84.dir/build.make:87: cmTC_2fb84] Error 1
gmake[1]: Leaving directory '/home/a/phylanx/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_2fb84/fast] Error 2

Source file was:
int main() { return 0; }

**Comment by hkaiser** [comment]
@sithhell Can we do something about the warning reported above? On 64bit systems all is well, but on 32bit systems the shift-count is larger than the size of the used hash value.
