### ISSUE TITLE
Statistics primitives to accept a tuple of integers as axis

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#835]
I like to ask for `amax`, `amin`, `min`, `var`, `std`, `logsumexp`, `prod`, `any` and `all` to accept a tuple of integers for their `axis` argument. Fo example, having:
```py
import numpy as np
from phylanx import Phylanx

@Phylanx
def max(x, axis, keepdims=False):
	return np.amax(x, axis, keepdims)
	
max(np.array([[[1,2,3,4],[5,6,7,8]]]),(-1,1))
```
should result in `[8]`. The same code works in NumPy calling it with named arguments, i.e. `return np.amax(x, axis=axis, keepdims=keepdims)`
If it is possible, I want 
```py
max(np.array([[[1,2,3,4],[5,6,7,8]]]),[-1,1])
```
to result the same. In my understanding having `axis` as an `ir::range` in Phylanx would cover both cases.

**Comment by hkaiser** [comment]
I distinctly remember implementing this (see: https://github.com/STEllAR-GROUP/phylanx/blob/master/phylanx/plugins/statistics/statistics_base_impl.hpp#L597-L646). Looks like it's not doing what it should, though :/

**Comment by scheherzade** [comment]
Pull request #847 should fix this issue.
