### ISSUE TITLE
numpy.squeeze

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#844]
provide primitive support for [numpy.squeeze](https://docs.scipy.org/doc/numpy/reference/generated/numpy.squeeze.html).

**Comment by parsa** [comment]
This is already covered by @taless474 in #781, #700, #673. Take a look at its test [`squeeze_operation.cpp`](https://github.com/STEllAR-GROUP/phylanx/blob/master/tests/unit/plugins/matrixops/squeeze_operation.cpp) and its [documentation entry](https://stellar-group.github.io/phylanx/docs/sphinx/branches/master/html/reference/phyhelp.html#squeeze) and let us know if it's missing some functionality.

**Comment by ct-clmsn** [comment]
@parsa thanks, i'll do a better job in the future double checking commits and documentation.
