### ISSUE TITLE
PhySL interpreter inserts 'random' nil into output

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#854]
I should add that `random` sometimes has `nil` somewhere in its output. In physl:
```
random(make_list(5,10), list("binomial", 3, .5))
```
produces:
```
[[2, 2, 3nil,
 0, 2, 1, 1, 1, 1, 2], [2, 2, 2, 0, 1, 1, 2, 1, 3, 2], [3, 2, 2, 1, 0, 1, 2, 2, 2, 0], [2, 0, 1, 2, 1, 3, 3, 1, 0, 2], [2, 1, 1, 2, 2, 2, 2, 2, 1, 1]]
```

_Originally posted by @taless474 in https://github.com/STEllAR-GROUP/phylanx/issues/827#issuecomment-471065529_

**Comment by hkaiser** [comment]
As stated in #827:
> I think I know what's happening. Do you use the physl interpreter with the -p/--print command line option? If yes, then the interpreter will print the overall result of the evaluation of the given expression (nil in this case), which will get interspersed with the output generated from the evaluation itself. We probably should use hpx::cout instead of std::cout in the interpreter to avoid this.

**Comment by taless474** [comment]
It works, thanks.
```console
cout(softmax([[1, 2, 33], [42, 5, 6]]))
```
```log
[[1.26642e-14, 3.44248e-14, 1], [1, 8.53305e-17, 2.31952e-16]]
nil
```
