### ISSUE TITLE
Add support for Python list comprehensions

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#911]
List comprehensions are really useful for Python users. I like to suggest `@Phylanx` to support it. An example can be:
```py
import numpy as np
from phylanx import Phylanx

@Phylanx
def fx(x):
	return [[i+1] for i in x]

fx([1,2,3,4])
```
### Expected result
```pytb
[[2], [3], [4], [5]]
```

**Comment by hkaiser** [comment]
@rtohid do you think this would be doable?

**Comment by rtohid** [comment]
@hkaiser PhySL, as far as I know, does not support generators but we can provide similar functionalities using loops and the append operation. Meanwhile, it seems that `append` primitive is broken (#914).

**Comment by hkaiser** [comment]
@rtohid Do we need generators for list comprehension? The result is just a list and not a pair of iterators anyways, so I think we can generated some equivalent code without losing generality. 

Also, I will look into the issue you reported for `append`.
