### ISSUE TITLE
Add support for slice accepting a list of indices

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#920]
The following code works properly:
```py
@Phylanx
def fx_1(x,index1,index2,index3):
	return slice(x,index1,index2,index3)
	
x = np.array([[[1, 1, 1], [2, 2, 2]],[[3, 3, 3], [4, 4, 4]],[[5, 5, 5], [6, 6, 6]]])

fx_1(x, [1,2], [0,1], [0,3])
```
and results in `[[[3 3 3]]]`.

It would be useful to have also this working:
```py
@Phylanx
def fx_2(x,indices):
	return slice(x,indices)
	
fx_2(x, [[1,2], [0,1], [0,3]])
```
In this way, we can always pass one argument to `slice` regardless of x's number of dimensions.

**Comment by hkaiser** [comment]
@taless474 would it work if we exposed a special primitive (e.g. `tuple_slice`) that implements this functionality? Without using a special name or any other means of conveying the intention of using the list passed as first (and only) argument as a list of indices we will not be able to disambiguate all possible indexing methods.

**Comment by taless474** [comment]
Having `tuple_slice` would work for me.
