### ISSUE TITLE
OpenSCoP backend produces wrong parameters

### ISSUE THREAD

**Issue by Yeahhhh** [STEllAR-GROUP/phylanx#947]
Wrong data was collected as OpenSCoP's parameters.

example input:
```
def kernel(A, B, N):
    if N < 8:
        for i in range(N, 9):
            B[i] = A[i] + B[i]
```
OpenSCoP's parameters shall contain these data.
```
  Name: "N"
```
OpenSCoP's parameters shall not contain these data. This codes has a bug, and placed these data in "parameters".
```
  Iterator: "i"
  Name: "A", "B"
```

This bug is fixed in "github.com:Yeahhhh/phylanx bd71f6c 2019-04-11", and shall be merged.

**Comment by hkaiser** [comment]
This has been fixed by merging #946. Closing.
