### ISSUE TITLE
Use SIMD data types for blaze::map operations

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#97]
See here for details:
* [Issue 38 - Introduce custom operations for vectors and matrices - BitBucket](https://bitbucket.org/blaze-lib/blaze/issues/38/introduce-custom-operations-for-vectors.)
* [Vector and Matrix Customization/The `map()` Functions - Blaze Documentation - BitBucket](https://bitbucket.org/blaze-lib/blaze/wiki/Vector%20and%20Matrix%20Customization#!the-map-functions)

**Comment by hkaiser** [comment]
Part of this was resolved by #110

**Comment by hkaiser** [comment]
This was fixed by merging #110
