### ISSUE TITLE
physl command line argument to print returned results

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#974]
Users can ask the physl interpreter to return a result that is lost. physl can perform a computations and return a results that are invisible or inaccessible to a user. This situation complicates remote code deployments. Adding a flag to physl that prints a return result would make fetching remotely deployed code possible.

Python-to-PhySL Example:

```
@Phylanx
def add(x, y):
    return x + y
```
translates to
```
(block(
    define(x, constant(1)),
    define(y, constant(1)),
    define(
        add,
        a,
        b,
        __add(a, b)),
    add(x, y))
)
```

If the phys interpreter runs, then the returned value is lost as it is not printed to stdout (with a `cout`). This current issue makes returning results from a remote physl deployment not possible with out users re-tooling their code. Adding a flag to the physl interpreter that prints the returned value would make remote execution possible, `--print-on-return`, `--remote`, or `--deployed` are some suggestions.

Printed results should be structured (json?). Returning unnamed values (ex: `return 1 + 1`) are returned as the computed value. In the case the returned value is a variable (`z = a + b; return z`) then the result should be printed as a tuple or dictionary mapping the value's variable name and it's value.

**Comment by hkaiser** [comment]
@ct-clmsn we already have the `--print` command line option that prints the overall result. Is that what you need? see: 
https://github.com/STEllAR-GROUP/phylanx/blob/master/examples/interpreter/physl.cpp#L239-L240

**Comment by ct-clmsn** [comment]
Will close this issue; I really need to query the database before cluttering up the issue tracker!

**Comment by hkaiser** [comment]
@ct-clmsn no worries, electrons are cheap ;-)
