### ISSUE TITLE
phylanx and lra infinite loop on plugin load

### ISSUE THREAD

**Issue by ct-clmsn** [STEllAR-GROUP/phylanx#987]
the lra code (examples/algorithms/lra/lra.cpp) in phylanx has been compiled in debug mode with gcc 7.3.0, with hpx (system malloc also in debug mode).

when lra runs, it hangs on hpx_init. gdb running lra operates sliently. when i've CTL-C'd gdb breaks on hpx/util/plugin/detail/dll_dlopen.hpp line 400 (hpx::util::plugin::dll::LoadLibrary).

i've added a print statement into line 408, recompiled hpx and lra from phylanx in debug mode, and when lra runs, the string 'libhpx_phylanxd.so' is printed repeatedly. i'm not sure if this is an issue with hpx or my libdl.

**Comment by ct-clmsn** [comment]
wrong line of code; the correct line is hpx/util/plugin/detail/dll_dlopen.hpp:297

**Comment by ct-clmsn** [comment]
stack trace:

hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
hpx::util::plugin::dll::get_directory @ hpx/hpx/util/plugin/detail/detail/dll_dlopen.hpp:327
hpx::util::find_prefix @ hpx/src/util/find_prefix.cpp:69
phylanx::detail::user_main_config @ phylanx/src/version.cpp:76
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
hpx_startup::user_main_config @ hpx/hpx_user_main_config.cpp:23
hpx::init @ hpx/hpx_init_impl.hpp:77
hpx::init @ hpx/hpx_init_impl.hpp:95
hpx::init @ hpx/hpx_init_impl.hpp:112
main @ lra/lra.cpp:99

**Comment by ct-clmsn** [comment]
gdb stack trace
```
(gdb) b hpx::util::plugin::dll::LoadLibrary
(gdb) r
BreakPoint 1, hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
(gdb) bt
hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
hpx::util::plugin::dll::get_directory @ hpx/hpx/util/plugin/detail/detail/dll_dlopen.hpp:327
hpx::util::find_prefix @ hpx/src/util/find_prefix.cpp:69
phylanx::detail::user_main_config @ phylanx/src/version.cpp:76
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
hpx_startup::user_main_config @ hpx/hpx_user_main_config.cpp:23
hpx::init @ hpx/hpx_init_impl.hpp:77
hpx::init @ hpx/hpx_init_impl.hpp:95
hpx::init @ hpx/hpx_init_impl.hpp:112
main @ lra/lra.cpp:99

(gdb) info threads
* 1 Thread 'lra' hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
```
LoadLibrary is called repeatedly (infinite loop).

**Comment by ct-clmsn** [comment]
gdb stack trace
```
(gdb) b hpx::util::plugin::dll::LoadLibrary
(gdb) r
BreakPoint 1, hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
(gdb) bt
hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
hpx::util::plugin::dll::get_directory @ hpx/hpx/util/plugin/detail/detail/dll_dlopen.hpp:327
hpx::util::find_prefix @ hpx/src/util/find_prefix.cpp:69
phylanx::detail::user_main_config @ phylanx/src/version.cpp:76
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
hpx_startup::user_main_config @ hpx/hpx_user_main_config.cpp:23
hpx::init @ hpx/hpx_init_impl.hpp:77
hpx::init @ hpx/hpx_init_impl.hpp:95
hpx::init @ hpx/hpx_init_impl.hpp:112
main @ lra/lra.cpp:99

(gdb) info threads
* 1 Thread 'lra' hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
```
LoadLibrary is called repeatedly (infinite loop). Inserting a debugging print statement into hpx::util::plugin::dll::LoadLibrary:71 for the 'prefix' variable ('prefix.empty()') will cause the 'lra' program to repeatedly print `libhpx_phylanxd.so`.

**Comment by ct-clmsn** [comment]
Here is the output of a gdb trace of this issue.

```
(gdb) b hpx::util::plugin::dll::LoadLibrary
(gdb) r
BreakPoint 1, hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
(gdb) bt
hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
hpx::util::plugin::dll::get_directory @ hpx/hpx/util/plugin/detail/detail/dll_dlopen.hpp:327
hpx::util::find_prefix @ hpx/src/util/find_prefix.cpp:69
phylanx::detail::user_main_config @ phylanx/src/version.cpp:76
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
phylanx::detail::user_main_config @ phylanx/src/version.cpp:95
hpx_startup::user_main_config @ hpx/hpx_user_main_config.cpp:23
hpx::init @ hpx/hpx_init_impl.hpp:77
hpx::init @ hpx/hpx_init_impl.hpp:95
hpx::init @ hpx/hpx_init_impl.hpp:112
main @ lra/lra.cpp:99

(gdb) info threads
* 1 Thread 'lra' hpx::util::plugin::dll::LoadLibrary @ hpx/hpx/util/plugin/detail/dll_dlopen.hpp:291
```

LoadLibrary is called repeatedly (infinite loop). Inserting a debugging print statement into LoadLibrary `hpx/hpx/util/plugin/detail/dll_dlopen.hpp:295` for the 'dll_name' variable (and 'dll_name.empty()') will cause the 'lra' program to repeatedly print `0     libhpx_phylanxd.so`.

**Comment by ct-clmsn** [comment]
something strange is going on at link time. when a full path is provided to the compiler of the hpx libraries this issue is resolved.

> g++ ... -L$(HPX_DIR) -lhpx_init -lhpx_wrap ...

doing something like that will result in either a pcond_wait deadlock or the infinite loop when plugins are loaded by phylanx.

> g++ ... -l/hpx_dir/lib/hpx_init.a -l/hpx_dir/lib/hpx_wrap.a ...

using a build command like that resolves both issues.

**Comment by hkaiser** [comment]
@ct-clmsn Thanks for figuring this out. However I have to admit that I don't understand why this could cause any issues except that there are several (possibly stale) versions of HPX found on your system and the linker picks the wrong one when you do `-L$(HPX_DIR) -lhpx_init ...`.

**Comment by ct-clmsn** [comment]
@hkaiser I agree, this is a really strange behavior. The following link from 2016 demonstrates the pcond_wait problem that I had experienced earlier in the summer: [link](http://mail.cct.lsu.edu/pipermail/hpx-users/2016-February/000672.html). The debugging process required looking at the cmake commands for the 1d_stencil_1 program in HPX and comparing them against a small test program.
