### ISSUE TITLE
Buildbot test failures for conv1d_operation tests

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#997]
The following tests FAILED:
	162 - tests.unit.plugins.keras_support.conv1d_operation (Failed)
	172 - tests.unit.plugins.keras_support.separable_conv1d_operation (Failed)

See: http://ktau.nic.uoregon.edu:8020/#/builders/7/builds/310/steps/14/logs/stdio

**Comment by hkaiser** [comment]
@taless474 would you be able to look into this?

**Comment by taless474** [comment]
Sure. I made the mistake to choose the same name for conv_indices_helper and pool_indices_helper. So I think after merging pool operations, convolutions were using pool_indices_helper indices and failed. I put them in the namespaces in #998. Please let me know if it is not a proper fix.
